### ISSUE TITLE
Requesting feature to choose Clang version

### ISSUE THREAD

**Issue by martinlicht** [include-what-you-use/include-what-you-use#1433] opened 2024-01-11 01:02 UTC
It seems that iwyu assumes that `clang++` on the local matches the version of Clang.

This potentially breaks iwyu when the appropriate version of Clang cannot be installed on the local machine for whatever reasons (e.g. installing the current version has broken my other compilers in the past). 

I suggest a feature to select the Clang version assumed by iwyu.

**Comment by kimgr** [comment] 2024-01-11 21:09
That's unfortunately not possible. IWYU uses the Clang libraries extensive to do its work, and those libraries are hardwired to their version of the built-in headers. This is tracked in issue #100. 

I think this should be closed as a duplicate of issue 100, but let me know if I'm misunderstanding something. Thanks!

**Comment by kimgr** [comment] 2024-01-21 21:25
Duplicate of #100.

**Closed by kimgr** 2024-01-21 21:25 UTC
