### ISSUE TITLE
[Regression 0.18 -> 0.20] IWYU incorrectly wants to remove <new> 

### ISSUE THREAD

**Issue by carlosgalvezp** [include-what-you-use/include-what-you-use#1229] opened 2023-04-04 08:41 UTC
Hi!

We are looking into bumping IWYU from 0.18 to 0.20 (btw, amazing job with templates, lots of FPs fixed!) and encounter the following problem:

```cpp
// foo.h
#include <new>
#include <utility>

template <typename Ref, typename... Args>
void construct(Ref& ref, Args&&... args)
{
    new (std::addressof(ref)) Ref(std::forward<Args>(args)...);
}
```
```cpp
// foo.cpp
#include "foo.h"

int main()
{
  int x;
  construct(x, 123);
}
```

Running IWYU with default settings results in the following:
```
foo.h should add these lines:

foo.h should remove these lines:
- #include <new>  // lines 1-1

The full include-list for foo.h:
#include <utility>  // for addressof, forward
---
```

If I remove `new`, the code no longer compiles.

**Comment by kimgr** [comment] 2023-04-07 11:26
Hehe, fun. It's not actually a regression, it's just a bug that was hidden because we attributed the new-expression to the expansion location (where `<new>` is not included, so no change required) instead of the template definition location (where we now, wrongfully, suggest that `<new>` should be removed).

The issue appears to be the use of `std::addressof` -- replacing it with `&ref` make IWYU understand what's going on.

I haven't found exactly where this decision is being made, still checking.

**Comment by kimgr** [comment] 2023-04-07 11:52
OK, so it's this little bit: https://github.com/include-what-you-use/include-what-you-use/blob/master/iwyu.cc#L2419.

When using a normal `&arg`, the resulting type will be a pointer and we get into the use-analysis branch.

When using `std::address_of(arg)`, the resulting type is a dependent-type (as we're in a template), which doesn't match any of the conditions set up for placement new.

Looking in Clang for patterns used to detect placement new, they're actually much more lenient, so I'm beginning to wonder if we should loosen the constraints here too. I think there is some overlap with aligned allocation (`operator new(size_t, std::align_val_t)`), but possibly we can tell the apart some other way.

**Comment by kimgr** [comment] 2023-06-24 12:07
@carlosgalvezp Please test with PR #1266 if you get a chance.

**Comment by carlosgalvezp** [comment] 2023-06-26 06:45
@kimgr Thanks for the fix! Will test it asap :)

**Comment by carlosgalvezp** [comment] 2023-07-05 08:46
@kimgr I have now tested the PR and works perfectly, IWYU now does not want to incorrectly remove `<new>`! Thanks again for the quick fix :smile:

**Comment by kimgr** [comment] 2023-07-06 19:39
Thanks for testing! Now fixed on master.

**Closed** 2023-07-06 19:39 UTC
