### ISSUE TITLE
iwyu chokes on boost/move/algorithm.hpp

### ISSUE THREAD

**Issue by Bu11etmagnet** [include-what-you-use/include-what-you-use#406] opened 2017-01-30 15:56 UTC
`#include <boost/chrono.hpp>
`

results in

```
Cycle in include-mapping:
  <boost/move/algorithm.hpp> ->
  <boost/move/algorithm.hpp>
llvm/tools/clang/tools/include-what-you-use/iwyu_include_picker.cc:844: Assertion failed: Cycle in include-mapping
```

Ubuntu's Boost 1.54 boost/move/algorithm.h does indeed include itself:

```
#ifndef BOOST_MOVE_ALGORITHM_HPP
#define BOOST_MOVE_ALGORITHM_HPP

#include <boost/move/detail/config_begin.hpp>

#include <boost/move/utility.hpp>
#include <boost/move/iterator.hpp>
#include <boost/move/algorithm.hpp>
#include <boost/detail/no_exceptions_support.hpp>

#include <algorithm> //copy, copy_backward
#include <memory>    //uninitialized_copy
```

I don't understand the logic of exempting "third_party" and "internal".

Maybe a one-length cycle could also receive a free pass.

**Comment by kimgr** [comment] 2017-01-31 20:07
Sigh. Sometimes Boost is wonderful, and sometimes I wonder what's going on.

> I don't understand the logic of exempting "third_party" and "internal"

IWYU started as a Google-internal project, and there are still some Googleisms hard-coded in it. It looks like Google puts all their third-party code in a root called `third_party`, so that's a convenient way of excluding code they have less control over. Outside of Google, this is less useful :-)

Thanks for the bug report, we should probably handle this more gracefully. Not sure how.

**Comment by Bu11etmagnet** [comment] 2017-02-01 16:41
Tried it with a file including `boost/optional.hpp` and got

```
Cycle in include-mapping:
  <boost/utility/in_place_factory.hpp> ->
  <boost/preprocessor/iteration/detail/iter/forward1.hpp> ->
  <boost/preprocessor/iteration/detail/iter/forward1.hpp>
llvm/tools/clang/tools/include-what-you-use/iwyu_include_picker.cc:844: Assertion failed: Cycle in include-mapping
```

This is even worse than `algorithm.h` because `algorithm.h` including itself is likely a mistake, but the cycle in `boost/preprocessor` might be intentional :(

**Comment by apollo13** [comment] 2017-02-08 14:53
What can be done to work around this? Boost seems to be pretty annoying :D

**Comment by Bu11etmagnet** [comment] 2017-02-09 11:32
I've done this privately:

```
diff --git a/iwyu_include_picker.cc b/iwyu_include_picker.cc
index 2436076..b17129d 100644
--- a/iwyu_include_picker.cc
+++ b/iwyu_include_picker.cc
@@ -831,7 +831,7 @@ void MakeNodeTransitive(IncludePicker::IncludeMap* filename_map,
     // in /internal/.  We could CHECK-fail in such a case, but it's
     // probably better to just keep going.
     if (StartsWith(key, "\"third_party/") ||
-        key.find("internal/") != string::npos) {
+        key.find("boost/") != string::npos) {
       VERRS(4) << "Ignoring a cyclical mapping involving " << key << "\n";
       return;
     }
```

although I'm sure this is not the right way to do it :)

**Comment by apollo13** [comment] 2017-02-09 12:16
I did the same thing before asking, but then it suggested to remove bost/bind.hpp and replaced it with the private header, not sure if that is caused by mapping issues?

**Comment by sgleizes** [comment] 2017-02-09 14:57
Having the same issue here.
I wonder, could this be implemented as another command line option after `-Xiwyu`, specifying an exclusion pattern or a plain directory name?

**Comment by arnetheduck** [comment] 2017-03-29 00:08
Same issue when including `boost::variant`:
```
Cycle in include-mapping:
  <boost/variant/detail/substitute.hpp> ->
  <boost/preprocessor/iteration/detail/iter/forward1.hpp> ->
  <boost/preprocessor/iteration/detail/iter/forward1.hpp>
/home/jacek.sieka/Downloads/src/llvm-4.0.0.src/tools/clang/tools/include-what-you-use/iwyu_include_picker.cc:844: Assertion failed: Cycle in include-mapping
```

**Comment by kimgr** [comment] 2017-05-06 15:07
I installed Boost 1.63 on my FreeBSD system in an attempt to reproduce this, but I can't.

```
$ cat tests/cyc.cc
#include <boost/chrono.hpp>
```
```
$ include-what-you-use -isystem /usr/local/include/ tests/cyc.cc

tests/cyc.cc should add these lines:

tests/cyc.cc should remove these lines:
- #include <boost/chrono.hpp>  // lines 1-1

The full include-list for tests/cyc.cc:
---
```
```
$ include-what-you-use -I /usr/local/include/ tests/cyc.cc

tests/cyc.cc should add these lines:

tests/cyc.cc should remove these lines:
- #include <boost/chrono.hpp>  // lines 1-1

The full include-list for tests/cyc.cc:
---
```

Can someone post a repro case with a source file using Boost, the Boost version and where it's installed, and the `include-what-you-use` invocation that triggers the problem?

Thanks!

**Comment by mblythe86** [comment] 2017-05-31 23:28
I may have commented in the wrong thread (see https://github.com/include-what-you-use/include-what-you-use/issues/424#issuecomment-305343298 ).

I can get failures from <boost/variant.hpp> starting with boost-1.62.  I tested using clang/llvm-4.0 and the iwyu branch clang_4.0, but I wouldn't be surprised if it failed on earlier versions of clang/llvm/iwyu, too.

I think the code to ignore errors in "Third Party" code just needs to be change to ignore errors in system headers (i.e. -isystem), if that's possible.

**Comment by kimgr** [comment] 2017-06-11 20:22
Here's the smallest repro I've found (with boost-1.63 on FreeBSD):

    $ cat cyc.cc
    #include <boost/variant.hpp>  // quoted include also triggers it

    $ include-what-you-use -isystem /usr/local/include cyc.cc

`/usr/local/include` is where the Boost headers are installed.

I still haven't managed to produce a reduced test case that triggers the problem.

**Comment by kimgr** [comment] 2020-11-08 18:48
Let's make #424 the main tracking issue for this. Closing this as a duplicate.

**Closed by kimgr** 2020-11-08 18:48 UTC
