### ISSUE TITLE
prevent expansion of boost/test

### ISSUE THREAD

**Issue by danielh2942** [include-what-you-use/include-what-you-use#1046] opened 2022-05-10 15:45 UTC
Hi, I am using IWYU on a project and for my unit tests I include the following:
```C++
#include <boost/test/unit_test.hpp>
#include <boost/test/test_tools.hpp>
```
then when I run the IWYU tool it expands the includes and includes a bunch of boost/preprocessor/ files, 
however when I swap them out the code no longer compiles as it does not properly expand to include the required header files

Is there a way to stop iwyu from expanding certain includes into specific header files?
I am using the boost imp files provided in this codebase FWIW

**Comment by kimgr** [comment] 2022-05-14 17:13
@danielh2942 You could try generating new mappings for your version of Boost using the script from https://github.com/include-what-you-use/include-what-you-use/pull/722.

I had hoped to reimplement that in Python at some point and bundle it with IWYU, but I haven't finalized anything yet.

**Comment by correaa** [comment] 2024-05-19 06:20
For illustration, this is the typical output for a Boost.Test cpp file that uses it in a canonical way:

```
/Users/user/boost-multi/include/mylib/adaptors/blas/test/trsm.cpp should add these lines:
#include <boost/preprocessor/arithmetic/limits/dec_256.hpp>
#include <boost/preprocessor/comparison/limits/not_equal_256.hpp>
#include <boost/preprocessor/control/expr_iif.hpp>
#include <boost/preprocessor/control/iif.hpp>
#include <boost/preprocessor/detail/limits/auto_rec_256.hpp>
#include <boost/preprocessor/logical/compl.hpp>
#include <boost/preprocessor/logical/limits/bool_256.hpp>
#include <boost/preprocessor/repetition/detail/limits/for_256.hpp>
#include <boost/preprocessor/repetition/for.hpp>
#include <boost/preprocessor/seq/limits/elem_256.hpp>
#include <boost/preprocessor/seq/limits/size_256.hpp>
#include <boost/preprocessor/tuple/elem.hpp>
#include <boost/preprocessor/variadic/limits/elem_64.hpp>
#include <boost/test/tools/old/interface.hpp>
#include <boost/test/tree/auto_registration.hpp>
#include <boost/test/unit_test_suite.hpp>
#include <boost/test/utils/basic_cstring/basic_cstring.hpp>
#include <boost/test/utils/lazy_ostream.hpp>

/Users/user/boost-multi/include/boost/multi/adaptors/blas/test/trsm.cpp should remove these lines:
- #include <boost/test/unit_test.hpp>  // lines 5-5
```

It somebody has a concrete way to generate a mapping file from this please let me know.

**Comment by correaa** [comment] 2024-05-19 07:35
This "imp" file `boost-test.imp` that I wrote seems to do at least part of the job.
It can be used from CMake as `cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_INCLUDE_WHAT_YOU_USE="include-what-you-use;-Xiwyu;--mapping_file=path/boost-test.imp`.

```json
[
    { "include": [ "<boost/preprocessor/arithmetic/limits/dec_256.hpp>", public, "<boost/test/unit_test.hpp>", public ] },
    { "include": [ "<boost/preprocessor/comparison/limits/not_equal_256.hpp>", public, "<boost/test/unit_test.hpp>", public ] },
    { "include": [ "<boost/preprocessor/control/expr_iif.hpp>", public, "<boost/test/unit_test.hpp>", public ] },
    { "include": [ "<boost/preprocessor/control/iif.hpp>", public, "<boost/test/unit_test.hpp>", public ] },
    { "include": [ "<boost/preprocessor/detail/limits/auto_rec_256.hpp>", public, "<boost/test/unit_test.hpp>", public ] },
    { "include": [ "<boost/preprocessor/logical/compl.hpp>", public, "<boost/test/unit_test.hpp>", public ] },
    { "include": [ "<boost/preprocessor/logical/limits/bool_256.hpp>", public, "<boost/test/unit_test.hpp>", public ] },
    { "include": [ "<boost/preprocessor/repetition/for.hpp>", public, "<boost/test/unit_test.hpp>", public ] },
    { "include": [ "<boost/preprocessor/repetition/detail/limits/for_256.hpp>", public, "<boost/test/unit_test.hpp>", public ] },
    { "include": [ "<boost/preprocessor/seq/limits/elem_256.hpp>", public, "<boost/test/unit_test.hpp>", public ] },
    { "include": [ "<boost/preprocessor/seq/limits/size_256.hpp>", public, "<boost/test/unit_test.hpp>", public ] },
    { "include": [ "<boost/preprocessor/tuple/elem.hpp>", public, "<boost/test/unit_test.hpp>", public ] },
    { "include": [ "<boost/preprocessor/tuple/elem_64.hpp>", public, "<boost/test/unit_test.hpp>", public ] },
    { "include": [ "<boost/preprocessor/variadic/limits/elem_64.hpp>", public, "<boost/test/unit_test.hpp>", public ] },
    { "include": [ "<boost/test/tools/old/interface.hpp>", public, "<boost/test/unit_test.hpp>", public ] },
    { "include": [ "<boost/test/tree/auto_registration.hpp>", public, "<boost/test/unit_test.hpp>", public ] },
    { "include": [ "<boost/test/utils/basic_cstring/basic_cstring.hpp>", public, "<boost/test/unit_test.hpp>", public ] },
    { "include": [ "<boost/test/utils/lazy_ostream.hpp>", public, "<boost/test/unit_test.hpp>", public ] },
    { "include": [ "<boost/test/unit_test_suite.hpp>", public, "<boost/test/unit_test.hpp>", public ] },
]
```

**Comment by firewave** [comment] 2024-07-08 07:03
This is essentially an duplicate of #227 albeit for a different part of Boost. I will elaborate on it in the other ticket.

**Comment by kimgr** [comment] 2024-07-09 19:41
@firewave Good call, I'll close this as a duplicate of #227. Let's collect all thoughts on Boost mappings there, since it's the oldest ticket.

**Closed by kimgr** 2024-07-09 19:41 UTC
