### ISSUE TITLE
Allow iwyu pragms to be specified in a mappings file

### ISSUE THREAD

**Issue by ThosRTanner** [include-what-you-use/include-what-you-use#336] opened 2016-07-02 09:22 UTC
At the moment, mappings files allow you to to map from include files to other include files or to specify a specific class maps to a specific file.

However, what you can't always do is to do something like this - which is fairly QT related and I'm not totally sure of the rights and wrongs of it.

Condier you have a dialog box, which you'd inherit from QDialog. You start writing something like

```

#include <QDialog>

class MyDialog: public QDialog {
    Q_OBJECT

```

at which point, with the current mapping files you get told you need to add `#include <QObject>`.

However, at least by what I understand from issue #335 to be convention, it's assumed that if you inherit from something that inherits from `QObject` then you shouldn't need to include the `QObject` header in your class because the `Q_OBJECT` macro and its friends are properties of the `QObject` class.

Now, either I'm missing something obvious (a skill at which I excel, sadly), or if not it'd be really nice to put something in the mappings file that says that` QObject.h` is exported by its clients.

In general this would be a nice thing to have because in general one doesn't have access to update the source of many 3rd party libraries (at least not in a way that would survive updates),

**Comment by kimgr** [comment] 2016-07-03 07:05
Duplicate of #292, closing.

**Closed by kimgr** 2016-07-03 07:05 UTC
