### ISSUE TITLE
How do you build IWYU on Windows?

### ISSUE THREAD

**Issue by e4lam** [include-what-you-use/include-what-you-use#684] opened 2019-05-01 15:40 UTC
How do you build IWYU on Windows? I've tried to follow the steps in README.md to avail but I can't get cmake to generate with either the default Visual Studio generator nor (preferably) the Ninja generator. I've done the following prerequisites as directed:
- Installed LLVM 8.0 from http://releases.llvm.org/8.0.0/LLVM-8.0.0-win64.exe
- Installed IWYU via git as directed and performed "git checkout clang_8.0"
- From the iwyu directory, performed: mkdir build; cd build
- Launched the Visual Studio 2017 x64 Native Tools Command Prompt
- Added (windows native variants) Ninja 1.8.2.git, CMake 3.13.2, and LLVM-8.0 bin directories to the path. These tools all work when I just type the executables in the command line.

Now here's the trouble I get with cmake attempt 1:
```
c:\cygwin\tmp\iwyu\build>cmake -DCMAKE_PREFIX_PATH="D:\Program Files\LLVM\lib" ..\include-what-you-use
-- Building for: Visual Studio 15 2017
-- IWYU: out-of-tree configuration
-- The C compiler identification is MSVC 19.16.27027.1
-- The CXX compiler identification is MSVC 19.16.27027.1
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/VC/Tools/MSVC/14.16.27
023/bin/Hostx86/x86/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/VC/Tools/MSVC/14.16.27
023/bin/Hostx86/x86/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/VC/Tools/MSVC/14.16.
27023/bin/Hostx86/x86/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/VC/Tools/MSVC/14.16.
27023/bin/Hostx86/x86/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:15 (find_package):
  Could not find a package configuration file provided by "LLVM" with any of
  the following names:

    LLVMConfig.cmake
    llvm-config.cmake

  Add the installation prefix of "LLVM" to CMAKE_PREFIX_PATH or set
  "LLVM_DIR" to a directory containing one of the above files.  If "LLVM"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!
See also "C:/cygwin/tmp/iwyu/build/CMakeFiles/CMakeOutput.log".
```

I tried looking in the cmake, llvm, and include-what-you-use directories and couldn't find any LLVMConfig.cmake nor llvm-config.cmake files.

I removed everything in build and try with the Ninja generator instead, same problem.

When I trying running cmake in a non-Visual Studio environment command prompt, I can sometimes get this error instead:
```
  The Clang compiler tool

    "D:/Program Files/LLVM/bin/clang++.exe"

  targets the MSVC ABI but has a GNU-like command-line interface.  This is
  not supported.  Use 'clang-cl' instead, e.g.  by setting 'CXX=clang-cl' in
  the environment.  Furthermore, use the MSVC command-line environment.
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.13/Modules/CMakeDetermineCXXCompiler.cmake:108 (CMAKE_DIAGNOSE_UNSUPPORTED_CLANG)

  CMakeLists.txt:13 (project)
```
However, if I try to follow these instructions, I can't actually link because I don't have a Visual Studio environment set up:
```
C:\cygwin\tmp\iwyu\build>cmake -G Ninja -DCMAKE_PREFIX_PATH="D:\Program Files\LLVM\lib" -DCMAKE_CXX_COMPILER="clang
-cl" ..\include-what-you-use
-- IWYU: out-of-tree configuration
-- The C compiler identification is Clang 8.0.0
-- The CXX compiler identification is Clang 8.0.0
-- Check for working C compiler: D:/Program Files/LLVM/bin/clang-cl.exe
-- Check for working C compiler: D:/Program Files/LLVM/bin/clang-cl.exe -- broken
CMake Error at C:/Program Files/CMake/share/cmake-3.13/Modules/CMakeTestCCompiler.cmake:52 (message):
  The C compiler

    "D:/Program Files/LLVM/bin/clang-cl.exe"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: C:/cygwin/tmp/iwyu/build/CMakeFiles/CMakeTmp

    Run Build Command:"C:/cygwin/usr/local/bin/ninja.exe" "cmTC_63122"
    [1/2] Building C object CMakeFiles\cmTC_63122.dir\testCCompiler.c.obj
    [2/2] Linking C executable cmTC_63122.exe
    FAILED: cmTC_63122.exe
    cmd.exe /C "cd . && "C:\Program Files\CMake\bin\cmake.exe" -E vs_link_exe --intdir=CMakeFiles\cmTC_63122.dir --manif
ests  -- CMAKE_LINKER-NOTFOUND /nologo CMakeFiles\cmTC_63122.dir\testCCompiler.c.obj  /out:cmTC_63122.exe /implib:cmTC_6
3122.lib /pdb:cmTC_63122.pdb /version:0.0  /machine:x64  /debug /INCREMENTAL /subsystem:console  kernel32.lib user32.lib
 gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
    RC Pass 1: command "rc /foCMakeFiles\cmTC_63122.dir/manifest.res CMakeFiles\cmTC_63122.dir/manifest.rc" failed (exit
 code 0) with the following output:
    The system cannot find the file specified
    ninja: build stopped: subcommand failed.




  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:13 (project)


-- Configuring incomplete, errors occurred!
See also "C:/cygwin/tmp/iwyu/build/CMakeFiles/CMakeOutput.log".
See also "C:/cygwin/tmp/iwyu/build/CMakeFiles/CMakeError.log".
```

**Comment by kimgr** [comment] 2019-05-03 05:35
Back when I used Windows, I only built IWYU in-tree, but we no longer strictly support that.

I think the problem is that the LLVM/Clang packages for Windows don't include the "SDK" (LLVM/Clang's internal headers and libraries), it's only the toolchain bits (compiler, tools, etc.)

The approach most likely to work should be to check out LLVM and Clang (I would recommend the monorepo here: https://github.com/llvm/llvm-project), follow their 'Getting started' guides to build them, and then point your IWYU `CMAKE_PREFIX_PATH` to the build directory. That's what I do on Linux and FreeBSD, and I believe it should work for Windows as well.

**Comment by jru** [comment] 2019-05-03 06:24
I had success both, building with the MSVC compiler and also with clang-cl on Windows. Just having LLVM installed *should* be enough for CMake to find it. 

If I type this from inside a Visual Studio Command prompt:
```
C:\iwyu\build>cmake -GNinja ..\
```
I get the following output:
```
-- IWYU: out-of-tree configuration
-- The C compiler identification is MSVC 19.16.27026.1
-- The CXX compiler identification is MSVC 19.16.27026.1
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using Debug VC++ CRT: MDd
-- IWYU: configuring for LLVM 8.0.0svn...
-- Found Git: C:/Program Files/Git/cmd/git.exe (found version "2.17.1.windows.2")
-- Configuring done
-- Generating done
-- Build files have been written to: C:/iwyu/build
```

Alternatively, I can specify `clang-cl` as the compiler, like this (mind the forward slashes!):
```
C:\iwyu\build>cmake ..\ -GNinja -DCMAKE_CXX_COMPILER="c:/Program Files/LLVM/bin/clang-cl.exe" -DCMAKE_C_COMPILER="c:/Program Files/LLVM/bin/clang-cl.exe"
```
To get this output:
```
-- IWYU: out-of-tree configuration
-- The C compiler identification is Clang 8.0.0
-- The CXX compiler identification is Clang 8.0.0
-- Check for working C compiler: c:/Program Files/LLVM/bin/clang-cl.exe
-- Check for working C compiler: c:/Program Files/LLVM/bin/clang-cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: c:/Program Files/LLVM/bin/clang-cl.exe
-- Check for working CXX compiler: c:/Program Files/LLVM/bin/clang-cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using Debug VC++ CRT: MDd
-- Performing Test SUPPORTS_BREPRO
-- Performing Test SUPPORTS_BREPRO - Success
-- IWYU: configuring for LLVM 8.0.0svn...
-- Found Git: C:/Program Files/Git/cmd/git.exe (found version "2.17.1.windows.2")
-- Configuring done
-- Generating done
-- Build files have been written to: C:/iwyu/build
```

To get a VS Command Prompt, I launch this batch file that comes with the VS installation (for x64 builds in this case):
`C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Auxiliary/Build/vcvars64.bat`

Hope it works!

**Comment by kimgr** [comment] 2019-05-03 06:35
That's great, couldn't be simpler! Maybe we should print the prefix path where LLVM was found so it's more obvious how to construct if you want to pass `CMAKE_PREFIX_PATH` explicitly (e.g. with multiple LLVM versions installed)

**Comment by e4lam** [comment] 2019-05-03 12:20
> I had success both, building with the MSVC compiler and also with clang-cl on Windows. Just having LLVM installed _should_ be enough for CMake to find it.

@jru Thanks for your reply! However, remove the -DCMAKE_PREFIX_PATH argument doesn't help either. I looked more into the problem which stems for these lines in the CMakeLists.txt:
```
  find_package(Clang CONFIG REQUIRED)
  find_package(LLVM CONFIG REQUIRED)
```
Neither of these lines work on my system because the required .cmake files don't exist on my system after installing http://releases.llvm.org/8.0.0/LLVM-8.0.0-win64.exe. On a Linux system which had clang installed into `/usr/local`, I found these in `/usr/local/lib/cmake/{clang,llvm}/*.cmake`. So I'm not sure where you have these installed on your Windows system?

Ah, I just found this on LLVM and cmake on Windows: https://stackoverflow.com/a/48954919 ... It looks like I really do need the source distribution to get those .cmake files. I'll try that now.

PS. I fixed the original post as I had pasted the wrong command line that I tried which was to do -DLLVM_CMAKE_PREFIX_PATH instead, which of course makes no sense.

**Comment by jru** [comment] 2019-05-06 07:37
> Ah, I just found this about LLVM and cmake on Windows: https://stackoverflow.com/a/48954919 ... It looks like I really do need the source distribution to get those .cmake files. I'll try that now.

Yes, that's the problem! I had forgotten that my LLVM installation was actually built locally from source, that's why my cmake files are all there.

But, honestly, that should be fixed on the LLVM side, as it doesn't make any sense to release it without those included..

**Comment by kimgr** [comment] 2019-05-06 14:58
@jru But are you positive your `LLVM*.lib` and `clang*.lib` and headers came from the public package and not from your local build?

I seem to recall it only contained the LLVM toolchain.

**Comment by jru** [comment] 2019-05-07 05:44
Well, that's the thing. I had installed the public package with prebuilt binaries a long time ago. But, I have since then overwritten it by doing `ninja install` from sources a couple of times, so I don't really know what's there anymore :)

In any case, I always build IWYU in-tree for simplicity and to bypass those issues.

**Comment by vahtis** [comment] 2019-09-24 10:37
Here is how I did it. I compiled x64 with Visual Studio 2019.
I was not able to compile iwyu with clang from windows package.
Only way was to use monorepo https://github.com/llvm/llvm-project.git
After cloning I used this page as reference https://clang.llvm.org/get_started.html
I did use cmake gui for creating solution files for visual studio.
I added entries for `LLVM_ENABLE_PROJECTS = clang` and `CMAKE_INSTALL_DIR = <path>`
After hitting generate I added `host=x64` as parameter for `-T`
After opening solution I compiled Clang libraries

When finished compiling Clang I moved to compiling IWYU.
Again I used cmake gui and set proper values for entries 
`CLANG_DIR = <path to llvm-project>build/lib/cmake/clang `
`LLVM_DIR = <path to llvm-project>build/lib/cmake/llvm`

Generated project and opened Visual Studio and everything compiled just fine.

**Comment by kimgr** [comment] 2019-09-28 15:17
@vahtis For future reference, it should work to just set `CMAKE_PREFIX_PATH` to `<path to llvm-project>/build` -- CMake is clever enough to look in `lib/cmake/...` for config modules. At least that's how I do it in my Linux environment.

**Comment by kimgr** [comment] 2019-10-27 08:31
I think this is as far as we'll get with this issue; there's nothing we can do in IWYU to simplify this unless LLVM/Clang start shipping an SDK package. Closing.

**Closed by kimgr** 2019-10-27 08:31 UTC

**Comment by kkpattern** [comment] 2022-07-26 07:40
I use following command to build IWYU with llvm in a same tree: `cmake -S llvm -B build -DLLVM_ENABLE_PROJECTS="clang;clang_extra_tools" -DLLVM_EXTERNAL_PROJECTS=iwyu -DLLVM_EXTERNAL_IWYU_SOURCE_DIR="../include-what-you-use" -DLLVM_TARGETS_TO_BUILD=X86 -Thost=x64`. IWYU and llvm both use clang-13 branch. Somehow the generated solution missing two include directories for include-what-you-use: `path\to\llvm-project\build\tools\clang\include` and `path\to\llvm-project\clang\include`. After I manually added these two include directories I can succesfully build include-what-you-use on Windows with Visual Studio.

**Comment by 988158** [comment] 2023-02-14 05:05
Hello:
I had the same error message:
`CMake Error at CMakeLists.txt:15 (find_package):
  Could not find a package configuration file provided by "LLVM" with any of
  the following names:

    LLVMConfig.cmake
    llvm-config.cmake

  Add the installation prefix of "LLVM" to CMAKE_PREFIX_PATH or set
  "LLVM_DIR" to a directory containing one of the above files.  If "LLVM"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!`

How did you fix this? Thanks

**Comment by frontfact** [comment] 2025-02-05 14:33
Hello,

To anyone still interested in compiling IWYU on Windows : LLVM does release the required files. For example look at the the release assets of the [`19.1.0`](https://github.com/llvm/llvm-project/releases/tag/llvmorg-19.1.0) you'll find an archive named `LLVM-19.1.0-Windows-X64.tar.xz`.

Download and extract it (it's several gigabytes). The resulting directory is named `LLVM_DIR` hereafter.

I was able to compile a release version of IWYU using the following batch script :

```
@echo off

set "LLVM_DIR=D:\LLVM-19.1.0-Windows-X64"
set "VSDIR=C:\Program Files\Microsoft Visual Studio\2022\Professional"

:: load msvc environment
PUSHD "%VSDIR%\VC\Auxiliary\Build"
    CALL vcvarsall.bat x64
POPD

:: create IWYU solution
:: Current working directory contains 'include-what-you-use', a git clone of the project
RMDIR /s /q build
MKDIR build
PUSHD build
    cmake -DCMAKE_PREFIX_PATH="%LLVM_DIR%" ..\include-what-you-use
    CALL include-what-you-use.sln
POPD
```

This opens a Visual Studio 2022 solution. Switch to Release configuration and generate the `include-what-you-use` project.

```
1>include-what-you-use.vcxproj -> C:\dev\iwyu\build\bin\Release\include-what-you-use.exe
```

Caveat : I had to tweak a library path generated by cmake :

C:\Program Files\Microsoft Visual Studio\2022\Enterprise\DIA SDK\lib\amd64\diaguids.lib

=> 

C:\Program Files\Microsoft Visual Studio\2022\Professional\DIA SDK\lib\amd64\diaguids.lib

**Comment by RT2Code** [comment] 2025-05-25 14:03
Thanks for the script @frontfact , it's very useful.

I turned it into a PowerShell script that builds the latest version of IWYU (0.24). It automatically downloads the LLVM and IWYU required files, compiles everything in one go and should work on your machine with no additional input required.

**build_iwyu.ps1**
```pwsh
$IWYU_VERSION = "0.24"
$LLVM_VERSION = "20.1.5"
$IWYU_URL = "https://github.com/include-what-you-use/include-what-you-use/archive/refs/tags/$IWYU_VERSION.zip"
$LLVM_DIR = "clang+llvm-$LLVM_VERSION-x86_64-pc-windows-msvc"
$LLVM_URL = "https://github.com/llvm/llvm-project/releases/download/llvmorg-$LLVM_VERSION/$LLVM_DIR.tar.xz"
$VSDIR = & "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe" -latest -property installationPath
$VSDIR = $VSDIR -replace '\\', '/'

$ProgressPreference = 'SilentlyContinue'
Invoke-WebRequest "$IWYU_URL" -OutFile "./iwyu.zip"
Invoke-WebRequest "$LLVM_URL" -OutFile "./llvm.tar.xz"

Expand-Archive -Path "./iwyu.zip" -DestinationPath "."
& tar -xvf "./llvm.tar.xz" -C "."
(Get-Content "$LLVM_DIR/lib/cmake/llvm/LLVMExports.cmake").Replace("C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/DIA SDK/lib/amd64/diaguids.lib", "$VSDIR/DIA SDK/lib/amd64/diaguids.lib") | Set-Content "$LLVM_DIR/lib/cmake/llvm/LLVMExports.cmake"

Push-Location "$VSDIR/VC/Auxiliary/Build"
cmd /c "vcvarsall.bat x64"
Pop-Location

Remove-Item -Recurse -Force build -ErrorAction SilentlyContinue
New-Item -ItemType Directory -Path build | Out-Null
Push-Location build
cmake -DCMAKE_PREFIX_PATH="../$LLVM_DIR" "../include-what-you-use-$IWYU_VERSION"
cmake --build . --config Release
Copy-Item -Path "bin/Release/include-what-you-use.exe" -Destination "../"
Pop-Location
```

**Comment by RT2Code** [comment] 2025-09-21 01:05
I updated the script for IWYU 0.26:

**build_iwyu.ps1**
```pwsh
$IWYU_VERSION = "0.26"
$LLVM_VERSION = "22.1.1"

$IWYU_URL = "https://github.com/include-what-you-use/include-what-you-use/archive/refs/tags/$IWYU_VERSION.zip"
$LLVM_DIR = "clang+llvm-$LLVM_VERSION-x86_64-pc-windows-msvc"
$LLVM_URL = "https://github.com/llvm/llvm-project/releases/download/llvmorg-$LLVM_VERSION/$LLVM_DIR.tar.xz"
$VSDIR = & "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe" -latest -property installationPath
$VSDIR = $VSDIR -replace '\\', '/'

Write-Host "Downloading IWYU $IWYU_VERSION and LLVM $LLVM_VERSION"

$ProgressPreference = 'SilentlyContinue'
Invoke-WebRequest "$IWYU_URL" -OutFile "./iwyu.zip"
Invoke-WebRequest "$LLVM_URL" -OutFile "./llvm.tar.xz"

Write-Host "Extracting IWYU and LLVM"

Expand-Archive -Path "./iwyu.zip" -DestinationPath "."
& tar -xvf "./llvm.tar.xz" -C "."
(Get-Content "$LLVM_DIR/lib/cmake/llvm/LLVMExports.cmake").Replace("C:/Program Files/Microsoft Visual Studio/2022/Enterprise/DIA SDK/lib/amd64/diaguids.lib", "$VSDIR/DIA SDK/lib/amd64/diaguids.lib") | Set-Content "$LLVM_DIR/lib/cmake/llvm/LLVMExports.cmake"

Write-Host "Building IWYU"

Push-Location "$VSDIR/VC/Auxiliary/Build"
cmd /c "vcvarsall.bat x64"
Pop-Location

Remove-Item -Recurse -Force build -ErrorAction SilentlyContinue
New-Item -ItemType Directory -Path build | Out-Null
Push-Location build
cmake -DCMAKE_PREFIX_PATH="../$LLVM_DIR" "../include-what-you-use-$IWYU_VERSION"
cmake --build . --config Release
Copy-Item -Path "bin/Release/include-what-you-use.exe" -Destination "../"
Pop-Location
Copy-Item -Path "./include-what-you-use-$IWYU_VERSION/iwyu_tool.py" -Destination "."

Pause
```
