### ISSUE TITLE
It shouldn't be necessary to include headers from parent class when base class overrides.

### ISSUE THREAD

**Issue by ThosRTanner** [include-what-you-use/include-what-you-use#1493] opened 2024-03-22 20:22 UTC
For instance something like this:

```
#include "Base_Class.hh"

class Child_Class : public Base_Class
{
    Return_Type &wibble(Type1 a, Type2 b) override;
}
```

*because* wibble is being overridden, Base_Class.hh must have defined wibble to be overridden, and it must also have sufficient definitions of Return_Type, Type1, Type2 to enable that to compile.

I can't see any purpose in forcing the inclusions again in Child_Class.hh as if the definition of wibble is changed to say use Type3 instead of Type2, your code won't compile even if it had the Type2 header in the first place. So you have to go change the include lines in more places than you actually need to.

I think this was discussed before, and let go as it wasn't easy to tell if something was being overridden, but now there's a keyword for it so it should be easy enough to detect.

**Comment by kimgr** [comment] 2024-03-23 11:42
Thanks -- duplicate of #105

**Closed by kimgr** 2024-03-23 11:42 UTC
