### ISSUE TITLE
Need a way to mark a header as not serving just to include things

### ISSUE THREAD

**Issue by vsapsai** [include-what-you-use/include-what-you-use#74] opened 2015-06-15 05:58 UTC
Originally reported on Google Code with ID 74

```
What version of the product are you using? On what operating system?
LLVM r160007, iwyu r357, Ubuntu 12.04 LTS x86.

Please provide any additional information below.
In the Mozilla codebase, there are some header files that are actually just a series
of macros to be used for preprocessor magic, not defining things.  Like this:

"""
EDITOR_ATOM(a, "a")
EDITOR_ATOM(abbr, "abbr")
EDITOR_ATOM(acronym, "acronym")
EDITOR_ATOM(address, "address")
EDITOR_ATOM(article, "article")
EDITOR_ATOM(aside, "aside")
...
"""
http://dxr.lanedo.com/mozilla-central/editor/libeditor/base/nsEditPropertyAtomList.h.html

Which is used thus:

"""
#define EDITOR_ATOM(name_, value_) nsIAtom* nsEditProperty::name_ = 0;
#include "nsEditPropertyAtomList.h"
#undef EDITOR_ATOM
...
#define EDITOR_ATOM(name_, value_) NS_STATIC_ATOM_BUFFER(name_##_buffer, value_)
#include "nsEditPropertyAtomList.h"
#undef EDITOR_ATOM
...
#define EDITOR_ATOM(name_, value_) NS_STATIC_ATOM(name_##_buffer, &name_),
#include "nsEditPropertyAtomList.h"
#undef EDITOR_ATOM
"""
http://dxr.lanedo.com/mozilla-central/editor/libeditor/html/nsEditProperty.cpp.html#l14

IWYU tries to move the #include lines around and removes two of the three, which obviously
breaks everything.  I tried marking the includes with "// IWYU pragma: keep", but that
only made it keep the third, while it still removed the other two.  There needs to
be some way to tell it to not touch the line at all -- perhaps pragma: keep should
do that.

Or if some way already exists, please add it to <http://code.google.com/p/include-what-you-use/source/browse/trunk/README.txt?r=260>.
 :)
```

Reported by `ayg@aryeh.name` on 2012-07-11 11:27:16

**Comment by kimgr** [comment] 2017-04-09 20:02
Possible duplicate of #45 and #109. Can't reproduce with a smaller example. Closing.

**Closed by kimgr** 2017-04-09 20:02 UTC
Labels: Priority-Medium, Type-Defect
