### ISSUE TITLE
IWYU suggests an include which is an implementation detail of standard library

### ISSUE THREAD

**Issue by loskutov** [include-what-you-use/include-what-you-use#648] opened 2019-02-06 23:35 UTC
Consider the following piece of code:
```c++
#include <vector>

struct s { int x; };

int main() {
    std::vector<s> v(10);
    v[1].x = 42;
}
```
It's correct: it uses the public interface of the `vector` template class, which is imported with `#include <vector>`. IWYU, however, does complain:
```
a.cpp should add these lines:
#include <memory>  // for allocator_traits<>::value_type

a.cpp should remove these lines:

The full include-list for a.cpp:
#include <memory>  // for allocator_traits<>::value_type
#include <vector>  // for vector
---
```

The reason for this dependency is probably `operator[]` which returns `vector::reference`, which in its turn is defined as `typedef typename _Alloc_traits::reference		reference;`. However, as the typedef is a part of the public interface, it looks like it's `vector`'s responsibility to provide the definition, not mine.

**Comment by kimgr** [comment] 2019-02-10 15:49
Thanks, we've apparently been working in related corners before: https://github.com/include-what-you-use/include-what-you-use/pull/214 (note this mentions how `<memory>` is suggested instead of an internal, and how something should be done about it). I think this might be a duplicate of #166.

**Comment by jru** [comment] 2019-02-13 07:26
This is a hard problem in general, because template instantiation happens with the canonical types only (after expanding typedefs and so on), and one has to keep track of the original type to report it back.

In IWYU, as far as I could see, there is limited handling for this kind of resugaring of types, and it is very platform-specific. That's why on Windows is even worse.

I spent some time looking into this in the past. Maybe I get the motivation to resurrect that WIP :)

**Comment by firewave** [comment] 2022-11-16 12:08
This also happens without `operator[]`:

```cpp
class A {
public:
    long long ll;
};

#include <list>

void f(std::list<A>& l)
{
    l.front().ll;
}
```

```
test.cpp should add these lines:
#include <memory>  // for allocator_traits<>::value_type

test.cpp should remove these lines:

The full include-list for test.cpp:
#include <list>    // for list
#include <memory>  // for allocator_traits<>::value_type
---
```

**Comment by firewave** [comment] 2023-02-13 16:09
FYI `clang-include-cleaner` is currently detecting these as unused includes.

**Comment by kimgr** [comment] 2023-03-05 13:48
Fixed on master as of https://github.com/include-what-you-use/include-what-you-use/commit/ffe6c3fe3a1dac9a4b577f4b07ef378ede933554 (and, as it turns out, probably a bit before that).

**Closed by kimgr** 2023-03-05 13:48 UTC
Labels: template-spill
