### ISSUE TITLE
0.19 --no_fwd_decl doesnt work on enum defined in .c

### ISSUE THREAD

**Issue by d-sauter** [include-what-you-use/include-what-you-use#1443] opened 2024-01-24 23:54 UTC
```
IWYU ANALYSIS FAILED!

(driver.h has correct #includes/fwd-decls)

driver.c should add these lines:
enum some_enum_E;

driver.c should remove these lines:

The full include-list for driver.c:
#include "driver.h"
enum some_enum_E;
---
```

driver.c
```
#include "driver.h"
enum some_enum_E;
...
enum some_enum_E
{
    VAR1 = 0x000U,
    VAR2 = 0x111U,
    VAR3 = 0x222U,
    VAR4 = 0x333U,
    VAR5 = 0x444U,
    VAR6 = 0x555U,
};
```

using 0.19 and passing `-Xiwyu --mapping_file=./my.imp -Xiwyu --no_default_mappings -Xiwyu --error -Xiwyu --no_fwd_decls`

Am I correct in saying with --no_fwd_decls it shouldnt be requiring this?

**Comment by bolshakov-a** [comment] 2024-01-27 15:08
Cannot reproduce on the latest master. My output is:
```
(driver.h has correct #includes/fwd-decls)

driver.c should add these lines:

driver.c should remove these lines:
- enum some_enum_E;  // lines 2-2

The full include-list for driver.c:
#include "driver.h"
```
both with and without `--no_fwd_decls`.

**Comment by kimgr** [comment] 2024-03-24 10:57
@d-sauter Have you had a chance to try a later IWYU version (0.22 was just released)? I can't reproduce on latest master either, so I'm inclined to close this as fixed.

**Comment by kimgr** [comment] 2024-07-07 19:29
No news is good news, I'm closing this as fixed as of https://github.com/include-what-you-use/include-what-you-use/releases/tag/0.22

**Closed by kimgr** 2024-07-07 19:29 UTC

**Comment by samwilksch** [comment] 2026-08-04 05:14
@kimgr 
I'm running IWYU v0.22 and have encountered this or a similar bug where it is trying to add enum forward declarations even though I'm running with `--no-fwd-decls`. My enums are un-scoped, so I think that this (possibly tied with https://github.com/include-what-you-use/include-what-you-use/issues/1934 ) means I get a compiler warning.

It looks like iwyu_output.cc initially honours `--no_fwd_decls` by promoting a forward-declaration use to a full-header use:
```cpp
if (!use->ignore_use() && GlobalFlags().no_fwd_decls) {
    ...
    use->set_full_use();
}
```

But later in the same processing pipeline, it can convert that full use back into a forward-declaration use when the definition appears later in the same file in the B2 condition:
```cpp
if (GetFileEntry(use->use_loc()) == GetFileEntry(use->decl()) &&
    !DeclIsVisibleToUseInSameFile(use->decl(), *use) &&
    DeclCanBeForwardDeclared(use->decl())) {
    ...
    use->set_forward_declare_use();
}
```

That later block does not check `GlobalFlags().no_fwd_decls`, so it can undo the earlier promotion. Perhaps that if statement should be `if (!GlobalFlags().no_fwd_decls && ...)`

I'm just a user of the tool not a developer, so apologies if this is the wrong place to post this or I'm barking up the wrong tree.

**Comment by bolshakov-a** [comment] 2026-08-04 08:47
@samwilksch, B2 step is pretty sane because, usually, you cannot include a file into itself for the complete definition of some class or enum, so if you name it before the definition, you have to put a forward-declaration. Maybe, you've encountered a location misattribution problem, like in #1934? Please provide a complete reproducer.

**Comment by samwilksch** [comment] 2026-08-05 05:19
@bolshakov-a the enum causing me an issue was declared inside a macro expansion, so I think I'm likely encountering the bug in #1934 
I will see if I can provide a minimal reproducer if I have time.
