### ISSUE TITLE
IWYU suggests to include bits/exception.h

### ISSUE THREAD

**Issue by Krzmbrzl** [include-what-you-use/include-what-you-use#1045] opened 2022-05-10 09:17 UTC
For the following code snippet
```cpp
#include <exception>

class MyException : public std::exception {
public:
    using::exception::exception;
}
```
IWYU suggests to include `<bits/exception.h>` and to remove `<exception>`. However, from what I think to know, the former is an internal header, whereas the latter is the standard header that should really be included.

include-what-you-use 0.12 based on clang version 9.0.1-10

**Comment by Krzmbrzl** [comment] 2022-05-11 17:45
Doesn't/Shouldn't it use a mapping of the STL by default? :eyes: 

Anyway, thanks for the hint - will try.

**Comment by jonesmz** [comment] 2022-05-12 01:06
The problem is "which stl" there are dozens of them.

**Comment by Febbe** [comment] 2022-06-17 02:26
> The problem is "which stl" there are dozens of them.

The one defined by: https://en.cppreference.com/w/ and the underlying iso cpp standard.

But it may be sufficient not to replace headers of the form `<identifier>` with anything `<path/identifier.h>`.

Or even better: have a map of all STL-Headers and never replace an STL-Header with a non STL-Header.

**Comment by martingalvan-nordic** [comment] 2022-08-08 13:54
Hi, I just ran into this issue myself. Is anyone actively looking at it?

**Comment by kimgr** [comment] 2022-08-08 15:28
As far as I can tell IWYU ships with mappings for `<exception>` since 0.16. You may be able to backport https://github.com/include-what-you-use/include-what-you-use/commit/1e09db4c.

**Comment by firewave** [comment] 2024-08-30 15:13
As mentioned in the previous comment this should be fixed. Also with 0.23 there are automatic mappings for these files.

I tried to reproduce it but it doesn't even compile for me:
```
test.cpp:5:10: error: no member named 'exception' in the global namespace; did you mean simply 'exception'?
    5 |     using::exception::exception;
      |          ^~~~~~~~~~~
      |          exception
/usr/lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/exception.h:60:9: note: 'exception' declared here
   60 |   class exception
      |         ^
```

Removing the code in question I only get correct includes since at least 0.20 (I currently have no older binary).

**Comment by kimgr** [comment] 2024-08-30 17:48
I edited the example to be:
```
#include <exception>

class MyException : public std::exception {
public:
    using std::exception::exception;
};
```

And that passes with `correct #includes/fwd-decls` on master. I don't dare post-date this fix, so I'll marked it fixed in next release (our mappings are very much cleaned out now after `@headername` fixups).

@firewave Thanks for raising this.

**Closed** 2024-08-30 19:15 UTC
