### ISSUE TITLE
iwyu 0.7 - iwyu_include_picker.cc:1047: Assertion failed

### ISSUE THREAD

**Issue by WildCard-25** [include-what-you-use/include-what-you-use#368] opened 2016-11-01 11:38 UTC
output from 0.7 verbose 9
>[ Use macro   ] D:/Repositories/shareaza/shareaza/Buffer.cpp:986:9: TRUE (from C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/atlmfc/include/afx.h:273:9)
Marked full-info use of macro TRUE (from C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/atlmfc/include/afx.h) at D:/Repositories/shareaza/shareaza/Buffer.cpp:986:9
Marked full-info use of macro DEBUG_NEW (from C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/atlmfc/include/afx.h) at D:/Repositories/shareaza/shareaza/Buffer.cpp:33:13
Adding mapping from \<sdkddkver.h> to 
D:\dev\private\llvm39\llvm\tools\clang\tools\include-what-you-use\iwyu_include_picker.cc:1047: Assertion failed: IsQuotedInclude(map_to) && "All map values must be quoted includes"

output from 0.6 verbose 9
>[ Use macro   ] D:/Repositories/shareaza/shareaza/Buffer.cpp:986:9: TRUE (from C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/atlmfc/include/afx.h:273:9)
Marked full-info use of macro TRUE (from C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/atlmfc/include/afx.h) at D:/Repositories/shareaza/shareaza/Buffer.cpp:986:9
Marked full-info use of macro DEBUG_NEW (from C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/atlmfc/include/afx.h) at D:/Repositories/shareaza/shareaza/Buffer.cpp:33:13
Marked use of include-file  (from \<math.h>) at Invalid location
Marked use of include-file  (from \<float.h>) at Invalid location

Looking back through the output, the only real difference is a missing slash at the end of the path for Buffer.cpp, which probably isn't good if this is the actual full path used and not just a pretty printing issue.

0.7
>[ Use macro   ] D:/Repositories/shareaza/**shareazaBuffer.cpp**:658:13 \<Spelling=D:/Repositories/shareaza/shareaza/Buffer.cpp:33:13>: DEBUG_NEW (from C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/atlmfc/include/afx.h:1468:9)
Marked full-info use of macro DEBUG_NEW (from C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/atlmfc/include/afx.h) at D:/Repositories/shareaza/**shareazaBuffer.cpp**:658:13 \<Spelling=D:/Repositories/shareaza/shareaza/Buffer.cpp:33:13>

0.6
>[ Use macro   ] D:/Repositories/shareaza/**shareaza/Buffer.cpp**:658:13 \<Spelling=D:/Repositories/shareaza/shareaza/Buffer.cpp:33:13>: DEBUG_NEW (from C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/atlmfc/include/afx.h:1468:9)
Marked full-info use of macro DEBUG_NEW (from C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/atlmfc/include/afx.h) at D:/Repositories/shareaza/**shareaza/Buffer.cpp**:658:13 \<Spelling=D:/Repositories/shareaza/shareaza/Buffer.cpp:33:13>

**Comment by vsapsai** [comment] 2016-11-14 00:32
Thanks for reporting the issue. I suspect it might be a problem with detecting direct include guards (as an example see [tests/cxx/macro_defined_by_includer-d2.h](https://github.com/include-what-you-use/include-what-you-use/blob/master/tests/cxx/macro_defined_by_includer-d2.h) and  [tests/cxx/macro_defined_by_includer-g2.h](https://github.com/include-what-you-use/include-what-you-use/blob/master/tests/cxx/macro_defined_by_includer-g2.h)).

Do you have a small repro case? If my guess is correct, just including some ATL-MFC headers should trigger the bug.

**Comment by matbech** [comment] 2016-11-19 23:44
Repro case:

Command line:
`include-what-you-use.exe -I "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.10.24629\include" -I "C:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\um" -I "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.10.24629\atlmfc\include" -DWIN32 -DNDEBUG -D_WINDOWS -D_USRDLL -w -x c++ -std=c++11 -fcxx-exceptions -fexceptions -fms-compatibility -fms-extensions -fmsc-version=1600 -Wno-invalid-token-paste -include stdafx.h "C:\Downloads\test.h"`

stdafx.h
```
#pragma once

#define _AFX_ALL_WARNINGS
#include <afx.h>

```

test.h
`#pragma once`

**Comment by kimgr** [comment] 2016-11-20 21:00
Thank you for that, I can reproduce the problem now.

**Comment by kimgr** [comment] 2016-12-04 20:20
I've boiled this down to the commit 04f1c925370d0f1a70642147f07c70a4c2bfb530 - "Handle internal headers guarded by macro and x-macros (fix issue #109)."

Looks like the combination of:

- Forced include with -include stdafx.h
- Control macro definition in stdafx.h
- Control macro dependency in afx.h

causes the map-to header (stdafx.h) to have no name in IWYU's analysis.

I'll see if I can boil it down to a portable repro case.

**Comment by kimgr** [comment] 2016-12-04 20:28
OK, here goes:

```
// header.h
#ifdef ENABLE_MAYBE
void Maybe() {
}
#endif

void Definitely() {
}

// pch.h
#define ENABLE_MAYBE
#include "header.h"

// test.cpp
(empty)

$ include-what-you-use -include pch.h test.cpp
...\include-what-you-use\iwyu_include_picker.cc:1043: Assertion failed: IsQuotedInclude(map_to) && "All map values must be quoted includes"
```

@vsapsai, can you take a look? I think you understand this better...

**Comment by vsapsai** [comment] 2016-12-04 23:48
Sure, will take a look. Thanks for the small repro case. And thanks for figuring out `-include` part, it would take me a long time to notice that.

**Comment by vsapsai** [comment] 2017-02-20 02:01
Pushed the fix to the master. If you are still encountering the assert, please reopen the issue.

**Closed by vsapsai** 2017-02-20 02:01 UTC
