### ISSUE TITLE
Add an option that never adds forward declarations

### ISSUE THREAD

**Issue by acmorrow** [include-what-you-use/include-what-you-use#475] opened 2017-08-24 17:25 UTC
Forward declarations are no longer stylish in the google style guide:

https://google.github.io/styleguide/cppguide.html#Forward_Declarations

It would be useful if IWYU had an option to always add the needed includes, rather than adding forward declarations.

**Comment by jcageman** [comment] 2017-08-26 09:25
Duplicate of #354

**Comment by kimgr** [comment] 2017-08-26 09:31
Closing as duplicate.

**Closed by kimgr** 2017-08-26 09:31 UTC
