### ISSUE TITLE
IWYU wants to pull in iosfwd "for std"

### ISSUE THREAD

**Issue by computerquip** [include-what-you-use/include-what-you-use#1251] opened 2023-04-29 04:59 UTC
I'm not sure what this means. For every file that has an std type of any kind, it keeps wanting to pull in iosfwd "for std". What does this mean, what causes it, and what can I do about it?

**Comment by kilroyd** [comment] 2023-04-29 17:51
It would help if you could specify the OS and compiler (i.e. standard libraries) that you're using, as well as IWYU version.

At a guess, does the code you are checking do `using namespace std`?

**Comment by computerquip** [comment] 2023-04-29 22:03
Sorry. I'm using Clang 16 from the LLVM APT repository on 18.04 with libgcc-s1 from the test tool repository (since the newer LLVM binaries require it and 18.04 is relatively old).

Also, yes, those files do use `using namespace std`. Is that the cause? I do have other headers that have std such as `<string>` if it's any consolation. What can I do about it?

**Comment by kilroyd** [comment] 2023-04-30 07:33
> those files do use using namespace std. Is that the cause?

Yes. `using namespace std` is a use of `std`, so IWYU is trying to ensure you have an appropriate include. The way it locates a header to satisfy the namespace use is not great. There's an existing issue #828 covering this, and I have PR #1213 open that tries to do better.

Note that there's specific advice against `using namespace std` in the C++ core guidelines (https://isocpp.org/wiki/faq/coding-standards "Should I use using namespace std in my code"). The advice is to either be explicit, or use using declarations (`using std::vector`) instead.

Hopefully my PR, or something similar can make it to IWYU 0.21

**Comment by computerquip-work** [comment] 2023-05-01 16:43
Alright, I'll close this since it's at best a duplicate of another issue. Thanks for the response, that cleared up my confusion.

**Closed** 2023-11-03 02:48 UTC
