### ISSUE TITLE
New feature request: iwyu config instead of pragmas

### ISSUE THREAD

**Issue by ggeorgiev** [include-what-you-use/include-what-you-use#301] opened 2016-05-10 14:29 UTC
What about if iwyu alternatively to the current pragma model offer ability "pragmas" or rules to be provided from a config file.

Say something like this: 
&lt;source_file_pattern&gt;
  &dash; keep
&nbsp;&nbsp;&lt;include_file_pattern1&gt;
&nbsp;&nbsp;&lt;include_file_pattern2&gt;

  &dash; expert
&nbsp;&nbsp;&lt;include_file_pattern1&gt;
&nbsp;&nbsp;&lt;include_file_pattern2&gt;

It might also have sections to declare private/public headers instead of doing so from the code and requiring recompilation to improve them ...

One big benefit I see for this is that it will allow providing rules for header files from 3rdparty code.

Also, wide use of IWYU might result in having pragmas in public header files, which equally as useful might be also it might be undesirable as well. Providing config file that does not annoy anybody who does not want to use it might be a more acceptable option for library maintainers.

**Comment by EugeneZelenko** [comment] 2016-05-20 00:54
Looks like duplicate of #292.

**Comment by kimgr** [comment] 2016-07-03 07:05
Closed as duplicate.

**Closed by kimgr** 2016-07-03 07:05 UTC
