### ISSUE TITLE
Regexes in mapping files not working

### ISSUE THREAD

**Issue by iven** [include-what-you-use/include-what-you-use#1243] opened 2023-04-19 09:56 UTC
I'm using the [newest libcxx.imp](https://github.com/include-what-you-use/include-what-you-use/blob/14e9b208914a84fcdf49bf9f5d08897a4b3dc4b8/libcxx.imp) in this repo, and the mappings seem to be correctly imported:
![图片](https://user-images.githubusercontent.com/56165/233038074-ab0df786-45f2-420b-aadd-94cf0e8642e7.png)
But in the result include list, `<__algorithm/copy.h>` and other headers with `__` prefix is not replaced with `<algorithm>` as expected:
![图片](https://user-images.githubusercontent.com/56165/233037612-5030c5dc-2d0d-43f0-ab76-33dbd1b9aeac.png)
Tested both on `clang_15` and `clang_16` branch.

Is this intended? What should I do if I want to replace headers like `<__algorithm/copy.h>` with `<algorithm>`?

(I digged into the code a bit, and found that `<__algorithm/copy.h>` is not added by `AddDirectInclude()`, while `ExpandRegexes()` only works on headers that added by `AddDirectInclude()`. Not sure it's by design or not.)

**Comment by kilroyd** [comment] 2023-04-19 19:17
Odd... it works for me (on master), but I don't think anything's significantly changed wrt imp handling. Do you have the IWYU command line that you're using? Also, have you tried to set `-Xiwyu --no_default_mappings` to see if it changes behavior?

**Comment by iven** [comment] 2023-04-20 04:17
I'm using `include-what-you-use -Xiwyu --no_fwd_decls -Xiwyu --mapping_file=libcxx.imp`. Setting `-Xiwyu --no_default_mappings` doesn't help.

I did some debuging and found that `<__algorithm/copy.h>` is not seen by `quoted_includes_to_quoted_includers_` in `ExpandRegexes()`, but can be seen by `GetCandidateHeadersForFilepathIncludedFrom()`, not sure why.

BTW, I'm using precompiled headers, I don't know if it's related.

**Comment by kilroyd** [comment] 2023-04-20 17:18
If you have iwyu source, you can use one of its test files, `iterator.cc`, which uses `<algorithm>`. I've been using it as a test case here.

```
$ include_what_you_use -Xiwyu --no_default_mappings -Xiwyu --mapping_file=libcxx.imp -I. tests/cxx/iterator.cc

(tests/cxx/iterator.cc has correct #includes/fwd-decls)

$ include-what-you-use -Xiwyu --no_default_mappings -I. tests/cxx/iterator.cc

tests/cxx/iterator.cc should add these lines:
#include <__algorithm/find.h>    // for find
#include <__memory/allocator.h>  // for allocator

tests/cxx/iterator.cc should remove these lines:
- #include <algorithm>  // lines 18-18

The full include-list for tests/cxx/iterator.cc:
#include <__algorithm/find.h>    // for find
#include <__memory/allocator.h>  // for allocator
#include <list>                  // for list, operator!=, __list_iterator
#include <vector>                // for vector
---
```

**Comment by iven** [comment] 2023-04-21 07:47
The test file with libcxx.imp works as expected:
```
include_what_you_use -Xiwyu --no_default_mappings -Xiwyu --mapping_file=libcxx.imp -I. tests/cxx/iterator.cc
```

I tried to compile my source code with precompiled headers disabled, but got:
```
Adding mapping from <sys/cdefs.h> to <features.h>
Adding mapping from <stdint.h> to <stdint.h>
Adding mapping from <bits/libc-header-start.h> to <stdint.h>
Adding mapping from <bits/typesizes.h> to <bits/types.h>
Adding mapping from <bits/time64.h> to <bits/types.h>
Adding mapping from <stddef.h> to <string.h>
Adding mapping from <bits/libc-header-start.h> to <string.h>
Adding mapping from <stddef.h> to <strings.h>
Adding mapping from <wchar.h> to <wchar.h>
Adding mapping from <stddef.h> to <wchar.h>
Adding mapping from <bits/libc-header-start.h> to <wchar.h>
Adding mapping from <bits/floatn-common.h> to <bits/floatn.h>
Adding mapping from <stddef.h> to <stdlib.h>
Adding mapping from <bits/libc-header-start.h> to <stdlib.h>
Adding mapping from <bits/waitflags.h> to <stdlib.h>
Adding mapping from <bits/waitstatus.h> to <stdlib.h>
Adding mapping from <bits/stdlib-float.h> to <stdlib.h>
Adding mapping from <stddef.h> to <sys/types.h>
Adding mapping from <sys/select.h> to <sys/types.h>
Adding mapping from <bits/byteswap.h> to <endian.h>
Adding mapping from <bits/uintn-identity.h> to <endian.h>
Adding mapping from <bits/endianness.h> to <bits/endian.h>
Adding mapping from <bits/select.h> to <sys/select.h>
Adding mapping from <stddef.h> to <alloca.h>
Adding mapping from <stddef.h> to <stdio.h>
Adding mapping from <bits/libc-header-start.h> to <stdio.h>
Adding mapping from <bits/stdio_lim.h> to <stdio.h>
Adding mapping from <bits/wctype-wchar.h> to <wctype.h>
Adding mapping from <limits.h> to <limits.h>
Adding mapping from <limits.h> to <limits.h>
Adding mapping from <bits/libc-header-start.h> to <limits.h>
Adding mapping from <bits/libc-header-start.h> to <math.h>
Adding mapping from <bits/math-vector.h> to <math.h>
Adding mapping from <bits/flt-eval-method.h> to <math.h>
Adding mapping from <bits/fp-logb.h> to <math.h>
Adding mapping from <bits/fp-fast.h> to <math.h>
Adding mapping from <bits/mathcalls-helper-functions.h> to <math.h>
Adding mapping from <bits/mathcalls.h> to <math.h>
Adding mapping from <bits/mathcalls-narrow.h> to <math.h>
Adding mapping from <bits/iscanonical.h> to <math.h>
Adding mapping from <stddef.h> to <time.h>
Adding mapping from <bits/errno.h> to <errno.h>
Adding mapping from <bits/setjmp.h> to <pthread.h>
Adding mapping from <stddef.h> to <sched.h>
Adding mapping from <bits/sched.h> to <sched.h>
Adding mapping from <bits/cpu-set.h> to <sched.h>
Adding mapping from <stddef.h> to <locale.h>
Adding mapping from <bits/locale.h> to <locale.h>
Cycle in include-mapping:
  <stdint.h> ->
  <stdint.h> ->
  <stdint.h>
/home/wukong/iwyu/include-what-you-use/iwyu_include_picker.cc:1108: Assertion failed: Cycle in include-mapping
```
The command line I used was:
```
IWYU_VERBOSE=8 include-what-you-use -Xiwyu --no_default_mappings -Xiwyu --no_fwd_decls -Xiwyu --mapping_file=libcxx.imp ...
```

**Comment by kimgr** [comment] 2023-04-21 16:26
The cycle in include mapping thing was fixed in iwyu for clang 16, so use that branch for better results.

**Comment by iven** [comment] 2023-04-23 02:51
I disabled PCH and switched to clang 16, and it works:

```
#include <memory>                         // for allocator
#include <optional>                       // for optional, nullopt
#include <string>                         // for basic_string, char_traits, operator==
#include <vector>                         // for vector
```

So can I use iwyu with PCH enabled? What is the correct way to use?

**Comment by kilroyd** [comment] 2023-04-23 16:19
I had a look into this the other day, and can reproduce the problem with PCH. It looks like regex mappings don't work as expected with precompiled headers.

For libcxx mappings, I suggest sticking with the previous version for now.

**Comment by kilroyd** [comment] 2023-04-24 19:58
Got to spend a bit more time looking at this. I think the problem is essentially as follows:

`iwyu_include_picker.cc::ExpandRegexes()` is supposed to iterate over the include files that we've seen, and check if they match the regexes that we have. If they do, `filepath_include_map_` is extended with that header. It is iterating over `quoted_includes_to_quoted_includers` which is setup by `AddDirectIncludes` when we encounter `#include`. For files pulled in via a PCH this never happens.

When `OneUse` tries to map a symbol, it uses `getFileEntry(use->decl_loc())`. This location can be set via a PCH, and if so, won't match anything `ExpandRegexes()` knows about.

What's bad is that PCH's are processed first - any standard include headers they pull in won't be processed later (because of multiple inclusion protection macros or `#pragma once`). So even if you explicitly `#include <algorithm>` in your file, `ExpandRegexes` won't see the nested `<__algorithm/find.h>` etc.

To fix this, we have to somehow iterate over `getFileEntry(use->decl_loc())` for all OneUse in `ExpandRegexes`, or get PCH processing to tell us about the headers.

**Comment by kimgr** [comment] 2024-03-11 20:14
Latest IWYU no longer accepts invocations with PCH enabled. See https://github.com/include-what-you-use/include-what-you-use/blob/master/docs/IWYUFAQ.md#why-doesnt-iwyu-work-with-precompiled-headers-enabled for reason and workaround.

**Closed by kimgr** 2024-03-11 20:14 UTC
Labels: pch
