### ISSUE TITLE
False positive: <ratio> required when using std::chrono::nanoseconds

### ISSUE THREAD

**Issue by carlosgalvezp** [include-what-you-use/include-what-you-use#1125] opened 2022-10-12 07:27 UTC
Applying IWYU on the following valid code:
```cpp
#include <chrono>

int main()
{
  using namespace std::chrono_literals;
  std::chrono::nanoseconds x{10ms};
}
```

Leads to the following warning from IWYU:

```
/tmp/main.cpp should add these lines:
#include <ratio>   // for nano

/tmp/main.cpp should remove these lines:

The full include-list for /tmp/main.cpp:
#include <chrono>  // for operator""ms, chrono_literals, nanoseconds
#include <ratio>   // for nano
---
```

**Comment by kimgr** [comment] 2022-10-13 19:51
Duplicate of #1061, closing

**Closed by kimgr** 2022-10-13 19:51 UTC

**Comment by carlosgalvezp** [comment] 2022-10-13 20:02
I wasn't sure if it was exactly the same issue, since in that case it's operator+ that causes trouble, whereas here is just using a type. But if you prefer to handle both cases in the case issue I'm fine with it!
