### ISSUE TITLE
Release compatible with LLVM/Clang 4.0

### ISSUE THREAD

**Issue by EugeneZelenko** [include-what-you-use/include-what-you-use#397] opened 2017-01-18 22:13 UTC
LLVM/Clang 4.0 was branched at January 12. I think will be good idea to create corresponding branch for IWYU.

**Comment by EugeneZelenko** [comment] 2017-03-09 22:45
4.0 final was tagged yestreday.

**Comment by brad0** [comment] 2017-03-20 00:35
As an OpenBSD package maintainer maintaining include-what-you-use for LLVM/Clang updates... please do.

**Comment by kimgr** [comment] 2017-03-20 06:02
We have a couple of important changes in flight at the moment, so we'd like to get those in before releasing. I can't make any timeline promises, but it should be 'soon'.

**Comment by arnetheduck** [comment] 2017-03-29 00:10
In the meantime, I've been using current master with llvm 4.0 and it "seems" to be working ;)

**Comment by kimgr** [comment] 2017-04-30 15:08
For the package maintainers watching this bug, would it be better for you to release IWYU against 4.0.0 or 4.0.1? I'm guessing most of you will uprev to 4.0.1 as soon as it's released?

**Comment by EugeneZelenko** [comment] 2017-04-30 20:39
Yes, 4.0.1 is close to release, so I'll build IWYU for that version. But I don't think that changes between 4.0.0 and 4.0.1 are significant.

**Comment by kimgr** [comment] 2017-04-30 20:46
The built-in headers are installed with the full version number under `/usr/lib/clang/X.Y.Z`, so IWYU won't run if built against a different version than the installed Clang.

**Comment by EugeneZelenko** [comment] 2017-05-01 02:42
We build IWYU in-tree, so installed version of LLVM/Clang doesn't matter.

**Comment by kimgr** [comment] 2017-05-01 07:55
The problem is at run-time, not build-time. If you also install the headers when installing IWYU you might be okay, but I worry that that might compromise Clang's package integrity. That is, what happens if you install first IWYU, then Clang, then uninstall IWYU? Will the builtin headers be removed?

**Comment by EugeneZelenko** [comment] 2017-05-01 14:43
We don't expose headers, but situation may be different for other usages.

**Comment by vsapsai** [comment] 2017-06-26 00:21
[LLVM 4.0.1 -final has been tagged](http://lists.llvm.org/pipermail/cfe-dev/2017-June/054349.html) but pre-built binaries aren't available yet. Should we wait for the binaries before building IWYU binaries? My suggestion is to wait for a week and see how it goes.

**Comment by springmeyer** [comment] 2017-07-06 18:25
I've been pulling from master while I wait for a 4.x tag. But I just noticed that this commit breaks my ability to do that: https://github.com/include-what-you-use/include-what-you-use/commit/bdcdaef51bcc6eb57faf8e15f2a1422ad6eb9e9b. Valid since I gather master is tracking master llvm, but wanted to let other people know. When building llvm 4.0.1 with https://github.com/include-what-you-use/include-what-you-use/commit/62414f4678dc1977f1411e836d42a60b8224f3c6 you should expect to see this error:

```
ld: library not found for -lLLVMBinaryFormat
clang: error: linker command failed with exit code 1 (use -v to see invocation)
[3260/4413] Building CXX object tools/lldb/tools/debugserver/source/CMakeFiles/lldbDebugserverCommon.dir/RNBRemote.cpp.o

```

**Comment by vsapsai** [comment] 2017-07-10 03:07
There is still no 4.0.1 binaries for Ubuntu and macOS binaries have some problems. Specifically, linking fails with

```
Undefined symbols for architecture x86_64:
  "_futimens", referenced from:
      llvm::sys::fs::setLastModificationAndAccessTime(int, std::__1::chrono::time_point<std::__1::chrono::system_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > >) in libLLVMSupport.a(Path.cpp.o)
ld: symbol(s) not found for architecture x86_64
```

I don't know in which macOS version `futimens` is available, it's not available in 10.12.5. Unarchived binaries directory is called `clang+llvm-4.0.1-x86_64-apple-macosx10.9.0` so I suspect it was available in 10.9.0.

Given all that I suggest to target LLVM+Clang 4.0.0. @kimgr, what do you think?

**Comment by kimgr** [comment] 2017-07-10 19:35
Works for me, I think we should just get something out there.

We can probably cherry-pick a number of additional fixes from master to get the most bang for the buck.

**Comment by kimgr** [comment] 2017-07-16 13:54
I've pulled everything relevant over from master to clang_4.0 locally, and built a Windows release. Seems to work fine. The commits I cherry-picked were:

4fc7f61 Commit first canonical README
71e41bf Remove docs/InstructionsForDevelopers.md
62414f4 Copy InstructionsForDevelopers to CONTRIBUTING
ee47cdf Make fix_includes understand Windows path names
8a9df40 Fix requiring allocator for getting container iterator with libc++. (#448)
39738d1 Map FILE to <stdio.h>
a2d8e28 Allow IWYU pragma: keep on forward declarations as an escape hatch for cases where IWYU incorrectly concludes that a forward declaration is not necessary and recommends its removal.
6c08711 Add .gitignore
b555a58 Don't lie about symbol regexes in the docs
-skipped: bdcdaef Update to reflect changes in LLVM.
45e1264 More complete usage instructions
db2391c Add test coverage for simple function pointer expressions
13cd948 Remove second-guessing for DeclRefExprs in CallExprs
78d0c15 Extract function pointer tests out of badinc
34baf6e Equate alias declarations and typedef in templates
669dd93 Break out typedef-in-template tests from badinc
301f8cc Accept methods hiding using declarations
c452de6 Let scrub-logs accept input from stdin
-skipped: f85a15b Remove TODOed assertions fixed by upstream Clang

I'd like to push this to the official clang_4.0 branch so we can build for the remaining platforms. Let me know pretty soon, before I lose my Windows box.

**Comment by vsapsai** [comment] 2017-07-16 21:03
If you've already cherry-picked the changes locally, I'm OK to include them into the clang_4.0 branch.

After you push these changes, it shouldn't take me more than 24 hours to test them (I've broken my Ubuntu box but it shouldn't take too long to restore it).

**Comment by kimgr** [comment] 2017-07-16 21:29
Thanks, I just pushed everything to https://github.com/include-what-you-use/include-what-you-use/tree/clang_4.0. I'll rebuild the Windows package from this branch again during the night.

**Comment by vsapsai** [comment] 2017-07-17 19:34
Tested latest clang_4.0 branch on Ubuntu - no errors. Tagged the `clang_4.0` branch.

**Comment by kimgr** [comment] 2017-07-19 20:52
I've uploaded an IWYU 0.8 for Windows x86 to the Google Drive storage.

**Comment by EugeneZelenko** [comment] 2017-07-19 20:54
Thank you, Kim!

Will be good idea to update https://include-what-you-use.org.

**Comment by kimgr** [comment] 2017-07-19 20:58
Yes, we're working to get binaries for all the platforms built, and then we can update the site.

**Comment by vsapsai** [comment] 2017-07-24 02:10
Uploaded to the Google Drive storage Ubuntu binary, macOS binary, source tarball. @kimgr, do you plan to have FreeBSD binary? For the reference for the period 2017-05-26 – 2017-07-24 downloads statistic is

file | downloads count
---- | -------------
0.7 sources | 389
0.7 Windows | 209
0.7 macOS | 111
0.7 Ubuntu | 108
0.4 sources | 107
0.6 sources | 93
0.5 sources | 77
...
0.7 FreeBSD | 20

**Comment by kimgr** [comment] 2017-07-24 06:09
I was planning to, but maybe that time is better spent maintaining a proper freebsd port. Let's go over the site and release. If there's demand for a bsd build, we can always add it later.

**Comment by vsapsai** [comment] 2017-08-03 18:54
New release is deployed to [include-what-you-use.org](https://include-what-you-use.org)

**Closed by vsapsai** 2017-08-03 18:54 UTC
