### ISSUE TITLE
iwyu-0.9 fails to find std include and aborts with assertion failure

### ISSUE THREAD

**Issue by dpelle** [include-what-you-use/include-what-you-use#534] opened 2018-04-01 08:43 UTC
I just built include-what-you-use-0.9 on Ubuntu-16.04 using:
```
$ sudo apt-get install libclang-5.0-dev
$ git clone https://github.com/include-what-you-use/include-what-you-use.git
$ cd include-what-you-use
$ git checkout clang_5.0
$ mkdir build
$ cd build
$ cmake -DIWYU_LLVM_ROOT_PATH=/usr/lib/llvm-5.0 ..
$ make -j8
$ sudo make install
```
It built without errors, good.

I then went into the directory where I have compile_commands.json for my project and ran:

```
$ iwyu_tool.py -p .
In file included from ...snp....cpp:12:
...snip....:15:10: fatal error: 'sstream' file not found
#include <sstream>
         ^~~~~~~~~
Cycle in include-mapping:
  <boost/phoenix/support/detail/iterate.hpp> ->
  <boost/phoenix/operator/detail/cpp03/mem_fun_ptr_eval_result_of.hpp> ->
  <boost/phoenix/operator/detail/cpp03/mem_fun_ptr_eval_result_of.hpp>
/home/dope/sb/include-what-you-use/iwyu_include_picker.cc:845: Assertion failed: Cycle in include-mapping
Aborted (core dumped)
...
```
There are 2 issues here:
* iwyu does not find the std c++ header <ssteam> for some reasons
* iwyu aborts with an assert failure (which looks similar to #424)

Did I miss any steps when installing include-what-you-use?

include-what-you-use used to provide binary releases, but not
anymore as of version 0.9. The binary releases were convenient
in my opinion. Any chance of producing binary releases again?
Compiling iwyu from sources may be fine in theory, but it looks like
too many things can go wrong when building it.

**Comment by kimgr** [comment] 2018-04-01 19:53
First, to be clear: we no longer have bandwidth or machine power to provide binary releases. The best way to help improve is to work on packaging for your platform. Packagers are typically not associated with the include-what-you-use project, for good or bad.

As to the issues;

1) `<sstream>` is a C++ standard ilbrary header -- IWYU has no influence over those, it just includes whatever standard library headers are installed on the machine. You should be able to use `include-what-you-use -v` to print information about what system compiler Clang and thereby IWYU finds or not.

2) I don't think there's a way to to build IWYU with assertions disabled, and I don't think the mapping or cycle detection code has changed, so I can only assume this is caused by a Boost upgrade. It does look like 424, it would be nice to get that working.

**Comment by kimgr** [comment] 2022-12-16 21:25
Closing this as a duplicate of #424, now fixed.

**Closed by kimgr** 2022-12-16 21:25 UTC
