### ISSUE TITLE
iwyu recommands to substitute an official C header by something else

### ISSUE THREAD

**Issue by sommerluk** [include-what-you-use/include-what-you-use#1163] opened 2022-12-26 15:01 UTC
Using the struct `tm` in a file, I get the following message:

```
[…] should add these lines:
#include <bits/types/struct_tm.h>           // for tm

[…] should remove these lines:
- #include <time.h>  // lines 34-34
```

However, as far as I understand, `<time.h>` is the correct include for struct `tm` in the C standard, isn’t it?

On my system, there are various `time.h` files, but  `/usr/include/time.h` reads as:
```C
[…]
/*
 *	ISO C99 Standard: 7.23 Date and time	<time.h>
 */
[…]
#ifndef	_TIME_H
#define _TIME_H	1
[…]
/* Many of the typedefs and structs whose official home is this header
   may also need to be defined by other headers.  */
#include <bits/types/clock_t.h>
#include <bits/types/time_t.h>
#include <bits/types/struct_tm.h>
```

Nevertheless, shouldn’t still be `<time.h>` the correct include because the C standard defines it so?

**Comment by kimgr** [comment] 2022-12-26 17:56
I believe the mappings were updated to cover `struct tm` in IWYU 0.19. Which version are you using?

**Comment by sommerluk** [comment] 2022-12-26 18:33
```
iwyu --version
include-what-you-use 0.17 based on Ubuntu clang version 13.0.1-2ubuntu2.1
```

**Comment by sommerluk** [comment] 2022-12-26 18:38
Neither
```
// IWYU pragma: no_include "struct_tm.h"
```
nor
```
// IWYU pragma: no_include "bits/types/struct_tm.h"
```
prevents IWYU from claiming to include `<bits/types/struct_tm.h>`. Is there any workaround?

**Comment by kimgr** [comment] 2022-12-26 19:01
Try:
```
// IWYU pragma: no_include <bits/types/struct_tm.h>
```

The angle-quotes are part of the include name.

**Comment by sommerluk** [comment] 2022-12-26 23:56
> Try:
> 
> ```
> // IWYU pragma: no_include <bits/types/struct_tm.h>
> ```
Yes, that helps. Thanks!

**Comment by kimgr** [comment] 2022-12-27 13:06
Glad to hear it, thank you. I'm closing this bug as the problem is fixed on mainline.

**Closed by kimgr** 2022-12-27 13:06 UTC
