### ISSUE TITLE
Regression: Recommendation of header for functions not used directly

### ISSUE THREAD

**Issue by charlemagnelasse** [include-what-you-use/include-what-you-use#383] opened 2016-12-17 15:45 UTC
Switching from iwyu 3.7 (debian) to 3.9 caused recommendation of headers which only have function which are not directly used.

Here is an example script which can be used to generate the headers and source files for the test

    cat > bitops.h << EOF
    #include "swap.h"
    
    #define __be32_to_cpu(x) __swab32(x)
    #define ntohl(x) ___ntohl(x)
    #define ___ntohl(x) __be32_to_cpu(x)
    EOF
    
    cat > swap.h << EOF
    static inline unsigned int __fswab32(unsigned int val)
    {
    	return __builtin_bswap32(val);
    }
    
    #define __swab32(x) (__fswab32(x))
    EOF
    
    cat > test.c << EOF
    #include "bitops.h"
    
    #define foo(x, y) ({(x) - (y); })
    
    static int test(unsigned int a)
    {
    	return foo(ntohl(a), 1);
    }
    EOF
    
    iwyu test.c

The output shown with Debian iwyu 3.9 is:

    test.c should add these lines:
    #include "swap.h"    // for __fswab32
    
    test.c should remove these lines:
    
    The full include-list for test.c:
    #include "bitops.h"  // for ntohl
    #include "swap.h"    // for __fswab32
    ---

But __fswab32 is not used anywhere directly in test.c.

This is a heavily simplified version of a real world case.

**Comment by charlemagnelasse** [comment] 2016-12-17 15:52
Just tested with clang_3.9 branch 136736fca90ad10e20b2ef728f0d52286e93ca46 and can reproduce it

**Comment by sylvestre** [comment] 2016-12-17 15:55
> Maybe @sylvestre can tell us which upstream version is in his iwyu 3.7 and 3.9 debian package

Not sure what you mean. I am shipping releases from:
https://github.com/include-what-you-use/include-what-you-use/releases

**Comment by sylvestre** [comment] 2016-12-17 15:55
And I don't apply any patch on top of iwyu

**Comment by charlemagnelasse** [comment] 2016-12-17 16:15
clang_3.7 98f3e62d371ae602061951115efc3b75ff255824 doesn't have the problem
clang_3.8 f09b88aaa0b7bb88a7b36da2ba1cab233659df6e has the problem

First commit having the problem is cf225fcbdb8412c479aba79b1fdde5f39d883141 from clang_3.8

**Comment by charlemagnelasse** [comment] 2016-12-17 16:18
Just tested the master branch fed1b64f9030652c5dfe8d8e3f65a11d0dae728d and it also has the problem

**Comment by kimgr** [comment] 2016-12-17 16:24
Thanks for the excellent bug report! I think this is a duplicate of #358. I'm working on it.

**Comment by kimgr** [comment] 2017-02-07 20:04
This passes with a fix I have for #358, closing as duplicate.

**Closed by kimgr** 2017-02-07 20:04 UTC
