### ISSUE TITLE
option to generate full include-list

### ISSUE THREAD

**Issue by FransM** [include-what-you-use/include-what-you-use#494] opened 2017-10-16 19:33 UTC
It would be nice if there was an option to generate the full include-list in the output even if the file is considered to be correct.

Rationale is that the comments may be wrong and I want to obtain the updated list.

**Comment by kimgr** [comment] 2017-10-22 14:36
Related to #190

**Comment by FransM** [comment] 2017-10-22 14:44
Let me clarify my request.

Ideally I would like to have the comments that are generated by IWYU in my code

However over time it is likely that these are outdated as the code changes.
I don't want to manually maintain the list and I figured if IWYU would output the full include list even if the file is correct, fixincludes then could apply that. That way I could run IWYU+fixincludes on my codebase at regular intervals (or even as a pre-commit hook in git on every commit) and have the comments updated when needed.

**Comment by kimgr** [comment] 2017-10-22 14:56
OK, so then this is probably a duplicate of #75

**Comment by FransM** [comment] 2017-10-22 14:59
yes
any plans to add this?
any chance if I add e.g. --force-comments myself to get it accepted?
(btw this is not a promise to implement it, I haven't peeked into the source so not sure how much work it would be)

**Comment by kimgr** [comment] 2017-10-22 15:08
Patches definitely welcome! As long as there's proper test coverage so functionality doesn't regress, I'd be happy to integrate a change like this.

**Closed** 2021-10-01 04:31 UTC
