### ISSUE TITLE
Allow LLVM include order

### ISSUE THREAD

**Issue by purpleKarrot** [include-what-you-use/include-what-you-use#357] opened 2016-08-17 15:36 UTC
IWYU currently follows Google's include order guideline where system includes come before local includes (https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes). Most projects that I work with follow LLVM's approach, where local includes come before system includes (http://llvm.org/docs/CodingStandards.html#include-style).

**Comment by EugeneZelenko** [comment] 2016-09-02 23:41
I think .clang-format could be used to determine proper includes order.

**Comment by purpleKarrot** [comment] 2018-11-19 19:30
@bhupeshpant19jan I no longer care about what include order iwyu uses, because I can regroup the includes with clang-tidy afterwards by setting `IncludeBlocks` to `Regroup`.

**Comment by bhupeshpant19jan** [comment] 2018-11-22 04:58
But in general, what is the recommended order?
In my existing project it was Clang --> sysroot -->  libc++ ....  But I have changes to Clang --> libc++ --> sysroot, is this correct order?

**Comment by kimgr** [comment] 2018-11-22 06:31
This is the sort order IWYU imposes:
```
enum class LineSortOrdinal {
  PrecompiledHeader,  // Precompiled headers must come first in MSVC
  AssociatedHeader,  // x.h for x.cc
  AssociatedInlineDefinitions, // Not sure what this is
  QuotedInclude,  // "include.h"
  CHeader,  // Header from the libc
  CppHeader,  // Header from the C++ STL
  OtherHeader,  // Probably any other header (project or third-party)
  ForwardDeclaration  // Forward-declarations should come after includes
};
```

I'm not sure what you mean by "Clang" above, but I'm guessing you mean the builtin headers?

**Comment by kimgr** [comment] 2021-08-02 20:35
Closing as duplicate of #35.

**Closed by kimgr** 2021-08-02 20:35 UTC
