### ISSUE TITLE
iwyu crash on using declaration in derived class

### ISSUE THREAD

**Issue by edward-san** [include-what-you-use/include-what-you-use#501] opened 2017-11-22 00:22 UTC
Given this header file:

```
class A {};

class X: A
{
	using A::A;
};
```

When run with this:

```
include-what-you-use -Xiwyu -x c++ -std=c++11 -o /dev/null -c x.h
```

The output is:

```
include-what-you-use: /usr/lib/llvm-4.0/include/llvm/Support/Casting.h:236: typename llvm::cast_retty<X, Y*>::ret_type llvm::cast(Y*) [with X = clang::CXXConstructorDecl; Y = clang::NamedDecl; typename llvm::cast_retty<X, Y*>::ret_type = clang::CXXConstructorDecl*]: Assertion `isa<X>(Val) && "cast<Ty>() argument of incompatible type!"' failed.
```

I could reproduce this on the clang_4.0 branch.

I'm on Ubuntu 16.04 x64, apt-installed libclang-4.0 .

**Comment by kimgr** [comment] 2017-11-22 06:02
Duplicate of https://github.com/include-what-you-use/include-what-you-use/issues/402. This is fixed on trunk, closing.

**Closed by kimgr** 2017-11-22 06:02 UTC
