### ISSUE TITLE
False postive: Forward declaration suggested for template declaration with definition in specialization

### ISSUE THREAD

**Issue by glennvl** [include-what-you-use/include-what-you-use#1217] opened 2023-03-21 16:14 UTC
# Summary

I have a template class without implementation, and a specialization where the actual implementation lives. As is also used for `std::function`. Include-what-you-use incorrectly suggests to add a forward declaration for the template class without implementation.

# Source code

```c++
// static_function.hpp

namespace util {

template <typename TFunction, std::size_t StorageSize = sizeof(std::uintptr_t) * 3u>
class StaticFunction;

template <std::size_t StorageSize, typename TRet, typename... TArgs>
class StaticFunction<TRet(TArgs...), StorageSize>
{
    // implementation
};

}
```

```c++
// static_function.test.cpp

#include <static_function.hpp>

// unittests that use StaticFunction live here
```

# IWYU output

```text
[build] 3/4 Building CXX object tests/CMakeFiles/test_utils.dir/static_function.test.cpp.o
[build] Warning: include-what-you-use reported diagnostics:
[build]
[build] /home/glenn/projects/STM32F303-DISCOVERY/tests/static_function.test.cpp should add these lines:
[build] namespace util { template <typename TFunction, std::size_t StorageSize = sizeof(std::uintptr_t) * 3U> class StaticFunction; }
```

Note that the forward declaration suggested by IWYU not only does not make sense, it is also not valid C++ (because it contains the default template arguments).

# Extra information

Tested with two IWYU versions

 * `include-what-you-use 0.17 based on Ubuntu clang version 13.0.1-2ubuntu2.1`
 * built from master against clang 16

**Comment by kimgr** [comment] 2023-03-25 13:52
Could you share also what the uses in `static_function_test.cpp` look like?

**Comment by glennvl** [comment] 2023-03-25 16:27
> Could you share also what the uses in `static_function_test.cpp` look like?

See <https://gist.github.com/glennvl/c03845c3c6499af6e9aa8308e56f2247>

**Comment by kimgr** [comment] 2023-12-17 17:25
I can't reproduce on master (but none of the repro cases are really free-standing enough that I could test them without modification, so I can't say for sure if I'm trying the same thing). There's been a bunch of template improvements, so I'm going to close this as fixed. Please reopen with a reduced example if the problems persist.

**Closed by kimgr** 2023-12-17 17:25 UTC
