### ISSUE TITLE
False positive: IWYU wants <cmath> removed when using std::pow

### ISSUE THREAD

**Issue by carlosgalvezp** [include-what-you-use/include-what-you-use#918] opened 2021-05-17 08:40 UTC
Hi,

The following code:

```
#include <cmath>

float f(float x)
{
    return std::pow(x, 2.0F);
}
```

leads to IWYU wrongly requesting us to remove `cmath`:

```
Ignoring use of std::pow (c.cpp:5:12): built-in function
c.cpp should remove these lines:
- #include <cmath>
```

Do note that the code will not compile if we follow IWYU's suggestion.

**Comment by kimgr** [comment] 2021-05-22 15:31
I don't fully understand all the nuances, but there appear to be a multitude of different kinds of built-ins, and some of them actually do require a header, such as `pow`. I think this is bug in how we try to determine what's a built-in function in IWYU. I've found some interesting classification methods in https://github.com/llvm/llvm-project/blob/main/clang/include/clang/Basic/Builtins.h#L66, but it looks like we have to thread a `Builtin::Context` object all the way into `iwyu_output.h`. Hopefully that does not turn out to be difficult :).

**Comment by kimgr** [comment] 2021-05-22 17:24
@carlosgalvezp Please give the change in #920 a shot, it seems to work well for your reduced testcase here.

**Comment by kimgr** [comment] 2021-05-22 18:16
Duplicate of #776, closing.

**Closed by kimgr** 2021-05-22 18:16 UTC
