### ISSUE TITLE
IWYU fails to compile hpp file, with error unable to handle compilation, expected exactly one compiler job in

### ISSUE THREAD

**Issue by vikramojha89** [include-what-you-use/include-what-you-use#1247] opened 2023-04-21 16:56 UTC
While trying to run IWYU on hpp file, its giving above issue "unable to handle compilation, expected exactly one compiler job in"

The problem is it copies duplicate command, In log I can see it has two path for iwyu copied twice

Below is snippet for output
`"/path/iwyu/iwyu-0.16/install/glnxa64/bin/include-what-you-use" "-cc1" "-triple" "x86_64-unknown-linux-gnu" "-fsyntax-only" "-disable-free" "-disable-llvm-verifier" "-discard-value-names" "-main-file-name" "foo.hpp" "some_other_compiler_options" "c++header" "foo.cpp" ; "/path/iwyu/iwyu-0.16/install/glnxa64/bin/include-what-you-use" "-cc1" "-triple" "x86_64-unknown-linux-gnu" "-fsyntax-only" "-disable-free" "-disable-llvm-verifier" "-discard-value-names" "-main-file-name" "foo.hpp" "some_other_compiler_options" "c++header" "foo.cpp" ; `

Reproduction steps

### foo.hpp

`#include <iostream>
#include <vector>

int prettyprint();

void foo();`

### Command used
`python iwyu_tool.py -j12 -o iwyu -p compile_commands.json foo.hpp`

#### Compiler
clang -12 
OS: Debian 11

### Include-what-you-use
clang version 12.0.1
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir:  <path>
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/10
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/10
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64

**Comment by kimgr** [comment] 2023-04-21 18:02
`iwyu_tool.py` just reads `compile_commands.json`, looks up the input filename and invokes `include-what-you-use` with the corresponding compile command. So I suspect your `compile_command.json` has that double-command in it for `foo.hpp`. How did you generate it? The `;` separator makes me think CMake?

**Comment by vikramojha89** [comment] 2023-04-22 11:54
I tried debugging `iwyu_tool.py` [here ](https://github.com/include-what-you-use/include-what-you-use/blob/14e9b208914a84fcdf49bf9f5d08897a4b3dc4b8/iwyu_tool.py#L431 ) inside main  

`invocations = [
        Invocation.from_compile_command(e, extra_args) for e in compilation_db
    ]`

invocations.command returns exactly one command to execute.

**Comment by kimgr** [comment] 2023-04-22 15:44
Does it make any difference if you leave out `-j12`?

Could you show the entry from the compilation database for `foo.hpp`?

**Comment by vikramojha89** [comment] 2023-04-22 16:14
Hi Kim, 

I tried without -j12 it produced the same result, 

Here's, the content of compile_comands.json

`[{"file":"/local-ssd/vojha/Bvariant.ParameterWriter/matlab/src/sl_compile/variants/foo.hpp","directory":"/local-ssd/vojha/Bvariant.ParameterWriter/matlab/src/sl_compile","command":"/org/hub/share/sbtools/external-apps/llvm/llvm-16.0.0/install/deb11-64/bin/clang -c variants/foo.hpp -o /dev/null -Iexport/include -I../../src/sl_compile/include -I../../src/sl_compile -I../../src/include -I../../derived/glnxa64/src/include -I../include -I../../derived/glnxa64/builtin2_impls/sl_compile_builtinimpl/builtin1/include -I../../derived/glnxa64/builtin2_impls/sl_compile_builtinimpl/builtin1/ -I../../derived/glnxa64/src/sl_compile/include -isystem/local-ssd/vojha/org-hub/3rdparty/R2023a/8825604/glnxa64/boost/include -isystem/local-ssd/vojha/org-hub/3rdparty/R2023a/9115666/glnxa64/cpp11compat/include -isystem/local-ssd/vojha/org-hub/3rdparty/R2021b/7038509/glnxa64/range-v3/include -isystem/local-ssd/vojha/org-hub/3rdparty/R2023a/8690994/glnxa64/gmp/include -isystem/local-ssd/vojha/org-hub/3rdparty/R2022a/7215999/glnxa64/hdf5-1.8/include -isystem/local-ssd/vojha/org-hub/3rdparty/R2022b/8340505/glnxa64/jdk/include -isystem/local-ssd/vojha/org-hub/3rdparty/R2022b/8340505/glnxa64/jdk/include/linux -isystem/local-ssd/vojha/org-hub/3rdparty/R2023a/8551682/glnxa64/mpfr/include -isystem/local-ssd/vojha/org-hub/3rdparty/R2022a/7425118/glnxa64/nlohmann-json/include -isystem/local-ssd/vojha/org-hub/3rdparty/R2021a/5800303/glnxa64/tbb/include -DMX_INTERLEAVED_COMPLEX -Dmw_test_main=main -DNEEDS_SL_SERVICES_UNICODE_CONVERSIONS -DNEEDS_ICU_EXT_API -DNEEDS_USTRING_OSTREAM_OVERLOAD -DNEEDS_MX_LEGACY_API -DBOOST_CB_DISABLE_DEBUG -DBOOST_ASIO_DISABLE_EVENTFD -DBOOST_VARIANT_USE_RELAXED_GET_BY_DEFAULT -DBOOST_SPIRIT_THREADSAFE -DPHOENIX_THREADSAFE -DBOOST_THREAD_PROVIDES_FUTURE_CONTINUATION -DBOOST_THREAD_VERSION=5 -DBOOST_THREAD_USES_DATETIME -DBOOST_FILESYSTEM_DISABLE_STATX -DBOOST_MPL_CFG_NO_PREPROCESSED_HEADERS -DBOOST_MPL_LIMIT_VECTOR_SIZE=30 -DBOOST_MPL_LIMIT_MAP_SIZE=30 -DBOOST_LOG_DYN_LINK -DJAVA_JNI -DJAVA_ARCH=\\\"amd64\\\" -DTBB_AVAILABLE -DTBB_USE_GLIBCXX_VERSION=100300 -DTBB_USE_CAPTURED_EXCEPTION=0 -DSL_INTERNAL -DCGIR_HANDWRITTEN_HEADERS -DBUILDING_SL_COMPILE -O0 -pipe -pthread -fdebug-prefix-map=/local-ssd/vojha/Bvariant.ParameterWriter= -fPIC -std=c++17 -fvisibility=hidden -g -D_POSIX_C_SOURCE=199506L -fno-omit-frame-pointer -W -Wcast-align -Wimplicit-fallthrough=5 -Wall -Wwrite-strings -Wpointer-arith -Wcast-qual -Woverloaded-virtual -Wnon-virtual-dtor -pedantic -Wshadow -Wno-long-long -Wredundant-decls -Wno-ignored-qualifiers -DNEEDS_MW_BUILTIN_MACROS -DMWBOOST=mwboost -DMWBOOST_132=mwboost_132 variants/foo.hpp -Weverything -Wno-unsafe-buffer-usage -Wno-c++98-compat -Wno-c++98-compat-pedantic -Wno-exit-time-destructors -Wno-global-constructors -Wno-switch-enum -Wno-covered-switch-default -Wno-padded -Wno-float-equal -Wno-weak-vtables -fcomment-block-commands='addindex,anchor,callergraph,callgraph,cite,class,cond,endcond,copybrief,copydetails,copydoc,diafile,dir,docbookonly,enddocbookonly,dotfile,file,if,ifnot,elseif,else,endif,include,internal,endinternal,mwBuiltin,mwBuiltinFunction,mwCallsIntoMATLAB,mwCapability,mwClassName,mwDispatcherExtension,mwDispatcherExtensionPrecedence,mwDispatcherLoadModulePostInitRc,mwDoesNotCallMATLAB,mwDoesNotRaiseWarnings,mwDominantClass,mwDominantType,mwFCtrlState,mwIsInheritable,mwMayRaiseWarnings,mwModuleInitialize,mwModuleTerminate,mwMultiMVMLibrary,mwMultiMVMLibrary,mwMultiMVMSuitable,mwNargin,mwNargout,mwPackageFolder,mwToolboxLocation,mwVisibilityInPackage,package,refitem,retval,skip,skipline,snippet,snippetdoc,snippetlineno,test,thread,thread_safe_because,until,verbinclude,vhdlflow,xrefitem' -DMW_LIBTOOLING "}]`

**Comment by vikramojha89** [comment] 2023-04-25 16:31
Hi Kim,

Without -j option also it didn't work.

I was manually creating a compile_commands.json by fetching compiler options, filename and directory. (This works for *.cpp file)

I now used a compdb to genreate compile_commands .json for hpp file, it runs but still it doesn't give proper output

### Compile_commands.json

`[
{
  "directory": "/mathworks/devel/sandbox/vojha/exploring-cpp-modules/iwyu/build",
  "command": "/usr/bin/c++ -std=gnu++11 -o CMakeFiles/Foo.dir/foo.cxx.o -c /mathworks/devel/sandbox/vojha/exploring-cpp-modules/iwyu/foo.cxx",
  "file": "/mathworks/devel/sandbox/vojha/exploring-cpp-modules/iwyu/foo.cxx",
  "output": "CMakeFiles/Foo.dir/foo.cxx.o"
},

{
  "directory": "/mathworks/devel/sandbox/vojha/exploring-cpp-modules/iwyu/build",
  "command": "/usr/bin/c++ -std=gnu++11 -c /mathworks/devel/sandbox/vojha/exploring-cpp-modules/iwyu/foo.hpp",
  "file": "/mathworks/devel/sandbox/vojha/exploring-cpp-modules/iwyu/foo.hpp"
}
]
`

### CMake

`cmake_minimum_required(VERSION 3.10)

project(Foo)

set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_STANDARD_REQUIRED true)


add_executable(Foo foo.cxx)
target_link_libraries(Foo foo.hpp)
`

### Source File

#### foo.cxx
`#include "foo.hpp"

void prettyprint() {
    std::cout<<"Hello";
}

void foo() {
    std::cout<<"foo";
}

int main() {
    return 0;
}
`

#### foo.hpp

`#include <vector>
#include <iostream>

void prettyprint();

void foo();
`

**Comment by kimgr** [comment] 2023-04-26 18:56
> it runs but still it doesn't give proper output

What does this mean? Can you show the output you get?

**Comment by vikramojha89** [comment] 2023-04-27 03:25
ya sorry I missed the output

`In file included from /mathworks/devel/sandbox/vojha/exploring-cpp-modules/iwyu/foo.hpp:1:
In file included from /usr/lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/vector:64:
In file included from /usr/lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/allocator.h:46:
In file included from /usr/lib/gcc/x86_64-linux-gnu/10/../../../../include/x86_64-linux-gnu/c++/10/bits/c++allocator.h:33:
In file included from /usr/lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/ext/new_allocator.h:33:
In file included from /usr/lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/new:41:
In file included from /usr/lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/exception:147:
In file included from /usr/lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/exception_ptr.h:38:
/usr/lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/bits/cxxabi_init_exception.h:38:10: fatal error: 'stddef.h' file not found
#include <stddef.h>
         ^~~~~~~~~~
`

**Comment by kimgr** [comment] 2023-04-27 06:38
https://github.com/include-what-you-use/include-what-you-use#how-to-install

**Comment by kimgr** [comment] 2023-05-23 06:28
This turned into a duplicate of #100. Closing.

**Closed by kimgr** 2023-05-23 06:28 UTC
