### ISSUE TITLE
Include with no comment

### ISSUE THREAD

**Issue by alejandro-colomar** [include-what-you-use/include-what-you-use#1040] opened 2022-05-01 23:31 UTC
```
$ make lint-iwyu
LINT (iwyu)	tmp/src/man2/wait.2.d/wait.lint.iwyu.touch

/usr/include/x86_64-linux-gnu/sys/wait.h should add these lines:
#include <sys/types.h>             // for __pid_t, __id_t

/usr/include/x86_64-linux-gnu/sys/wait.h should remove these lines:
- #include <bits/types.h>  // lines 29-29

The full include-list for /usr/include/x86_64-linux-gnu/sys/wait.h:
#include <bits/types/siginfo_t.h>  // for siginfo_t
#include <bits/waitflags.h>        // for idtype_t
#include <bits/waitstatus.h>       // for __WIFCONTINUED, __WIFEXITED, __WIF...
#include <features.h>              // for __USE_MISC, __USE_XOPEN2K8, __THROWNL
#include <signal.h>  // lines 36-36
#include <sys/types.h>             // for __pid_t, __id_t
struct rusage;  // lines 129-129
---

tmp/src/man2/wait.2.d/wait.c should add these lines:
#include <signal.h>  // for pid_t

tmp/src/man2/wait.2.d/wait.c should remove these lines:

The full include-list for tmp/src/man2/wait.2.d/wait.c:
#include <sys/wait.h>
#include <signal.h>  // for pid_t
#include <stdint.h>  // for intmax_t
#include <stdio.h>   // for printf, perror
#include <stdlib.h>  // for exit, atoi, EXIT_FAILURE, EXIT_SUCCESS
#include <unistd.h>  // for _exit, fork, getpid, pause
---
make: *** [Makefile:388: tmp/src/man2/wait.2.d/wait.lint.iwyu.touch] Error 1
```

Apart from the bogus report regarding a glibc header...

I get a line that I need `<sys/wait.h>`, but I'm not getting the comment about why.
I know I need it because I'm calling wait(2), but it's weird that iwyu(1) isn't adding a comment for it.

Also, the report for adding `<signal.h>` is bogus.  There're already various includes that provide `pid_t` (and if I add the include, iwyu(1) reports that I should remove it!) (And if I sort the includes in alphabetic order, iwyu(1) returns to sanity and tells me everything is fine).

**Comment by kimgr** [comment] 2022-05-07 13:45
@alejandro-colomar If you run `include-what-you-use` with higher verbosity, maybe you can get a view into its decision process and/or where the symbol that's the basis for `// for xyz` gets lost?

**Comment by alejandro-colomar** [comment] 2022-07-24 20:18
Just for me to be able to easily reproduce it in the future, since I changed the page and now I can't reproduce it anymore in the current page.  Apply the following diff, to reproduce the bug:

```diff
diff --git a/man2/wait.2 b/man2/wait.2
index 4ed803d97..6ca50ebb5 100644
--- a/man2/wait.2
+++ b/man2/wait.2
@@ -647,11 +647,11 @@ $
 \&
 .\" SRC BEGIN (wait.c)
 .EX
+#include <sys/wait.h>
 #include <stdint.h>
-#include <stdio.h>
 #include <stdlib.h>
-#include <sys/wait.h>
 #include <unistd.h>
+#include <stdio.h>
 
 int
 main(int argc, char *argv[])
```

**Comment by alejandro-colomar** [comment] 2022-07-24 23:05
Oh, I get why :P  Similar to another issue I reported recently

```
alx@asus5775:~/src/linux/man-pages/man-pages$ make tmp/src/man2/wait.2.d/wait.lint-c.iwyu.touch EXTRA_IWYUFLAGS='-Xiwyu --verbose=9' | grep associated
Adding /usr/include/x86_64-linux-gnu/sys/wait.h as associated header for tmp/src/man2/wait.2.d/wait.c
Marked /usr/include/x86_64-linux-gnu/sys/wait.h as associated header of tmp/src/man2/wait.2.d/wait.c.
Mapped /usr/include/x86_64-linux-gnu/sys/wait.h to <signal.h> for pid_t (in associated header)
Mapped /usr/include/x86_64-linux-gnu/sys/wait.h to <signal.h> for pid_t (in associated header)
make: *** [lib/lint-c.mk:68: tmp/src/man2/wait.2.d/wait.lint-c.iwyu.touch] Error 1
```

**Comment by kimgr** [comment] 2022-07-25 17:28
OK, so let's close this is a duplicate of #1037

**Closed by kimgr** 2022-07-25 17:28 UTC
