### ISSUE TITLE
IWYU working on headers from one directory

### ISSUE THREAD

**Issue by taneLines** [include-what-you-use/include-what-you-use#651] opened 2019-02-27 15:47 UTC
If there is no way to do it now (I can't see it), is it possible to do IWYU work only with headers from some directory. I have my work repository where I have access to and want IWYU to work, but some headers are in another location, which I don't want to change. Manual work will be painful, because of amount of headers.

**Comment by kimgr** [comment] 2019-03-03 12:10
Can you please expand on this with a small example? I don't understand what you want to achieve.

**Comment by kimgr** [comment] 2019-03-03 12:36
OK, it looks like this is a duplicate of #349 -- let's close this and continue any discussion there.

**Closed by kimgr** 2019-03-03 12:36 UTC
