### ISSUE TITLE
Should IWYU add/request includes for virtual overrides?

### ISSUE THREAD

**Issue by mwoehlke-kitware** [include-what-you-use/include-what-you-use#1412] opened 2024-01-04 19:24 UTC
Recently, I posted an MR to add the following function to a project:
```c++
  int ProcessCommandLineArguments(
    const std::string& currentArg, size_t& idx,
    const std::vector<std::string>& allArgs) override;
```

IWYU scolded me for not including `<stddef.h>` (for the `size_t` in the above). (It should probably report `<cstddef>` instead, but that's another matter.)

However... this feels odd. Now, I can sort of understand that the whole point is to not rely on what's "the public API" of some headers... but that doesn't exactly apply here, because the only way `size_t` can cease to be part of the public API of whatever ancestor originally specified this method is by changing the signature, in which case my `overload` will be broken (and I will no longer be using `size_t`, at least in this overload).

Does it really make sense to redundantly `#include <cstddef>` for this sort of case? Or is this in line with the `using` exception (see #174)?

I couldn't find any information on this, so apologies if it's already covered somewhere.

**Comment by kimgr** [comment] 2024-01-04 21:19
See #105. I've been thinking about this off and on since then, but haven't really made any headway.

**Comment by kimgr** [comment] 2024-01-05 20:33
Cheers, I'll close this as a dupe of #105.

I think the `override` argument you give makes sense. It's somewhat murky waters... If I ever get something running, I can experiment with both and see what seems most useful.

**Closed by kimgr** 2024-01-05 20:33 UTC
