### ISSUE TITLE
IWYU suggests include self header

### ISSUE THREAD

**Issue by ryzzn** [include-what-you-use/include-what-you-use#662] opened 2019-03-13 06:00 UTC
file case: 

```c++
// macro.h
#define DEFINE_Y struct Y {}

// test.h
#include "macro.h"
struct X
{
  DEFINE_Y;
  Y y_;
};

// test.cpp
#include "test.h"
void foo() { X x; }
```

Execute IWYU without any options output this:

```
$/data/0/packages/include-what-you-use/build/bin/include-what-you-use test.cpp

test.h should add these lines:
#include "test.h"   // for X::Y

test.h should remove these lines:

The full include-list for test.h:
#include "macro.h"  // for F
#include "test.h"   // for X::Y
---

(test.cpp has correct #includes/fwd-decls)
```

In which, test.h should include test.h itself.

for branch: clang_7.0

**Comment by ryzzn** [comment] 2019-03-13 06:12
The key is use a separated macro header file.

**Comment by kimgr** [comment] 2019-03-14 18:23
Interesting. Could you run that with a higher verbosity level (`-Xiwyu -v7`) and see if you can learn why it's making that decision? Upload the file to this issue if you need help.

**Comment by ryzzn** [comment] 2019-03-15 12:05
@kimgr Thanks for your response! Here is the full output use `_Xiwyu -v7`, I'm interested in why it says: `test.h:5:3: warning: X::Y is defined in "test.h", which isn't directly #included.`. 

```
$/data/0/packages/include-what-you-use/build/bin/include-what-you-use -Xiwyu -v7 test.cpp
Setting verbose-level to 7
Search path: /usr/local/gcc-5.2.0/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/../../../../include/c++/5.2.0/x86_64-unknown-linux-gnu/ (system)
Search path: /usr/local/gcc-5.2.0/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/../../../../include/c++/5.2.0/backward/ (system)
Search path: /usr/local/gcc-5.2.0/lib/gcc/x86_64-unknown-linux-gnu/5.2.0/../../../../include/c++/5.2.0/ (system)
Search path: /data/0/packages/include-what-you-use/build/lib/clang/7.1.0/include/ (system)
Search path: /usr/local/include/ (system)
Search path: /usr/include/ (system)
Found include: <built-in>:-1 -> test.cpp
Added to main compilation unit: test.cpp
[ Exiting to  ] test.cpp:1:1
[ #include    ] "test.h" (test.h)
Found include: test.cpp:1 -> test.h
Adding test.h as associated header for test.cpp
Marked test.h as associated header of test.cpp.
Added an #include: test.cpp -> "test.h"
Added to main compilation unit: test.h
[ #include    ] "macro.h" (macro.h)
Found include: test.h:1 -> macro.h
Added an #include: test.h -> "macro.h"
[ Exiting to  ] test.h:2:1
[ Use macro   ] test.h:4:3: F (from macro.h:1:9)
Marked full-info use of macro F (from macro.h) at test.h:4:3
[ Exiting to  ] test.cpp:2:1
Intends-to-provide for test.cpp:
   test.cpp
   test.h
Intends-to-provide for test.h:
   test.h
   macro.h
Intends-to-provide for macro.h:
   macro.h
test.h:3:8: (1) [ CXXRecordDecl ] 0x32d6da8 struct X {}
test.h:5:5: (2) [ FieldDecl ] 0x32d7150 X::Y y_
test.h:5:3: (3) [ RecordType ] 0x32d7000 struct X::Y
Marked full-info use of decl 0x32d6f60 X::Y (from test.h:4:3 <Spelling=./macro.h:1:18>) at test.h:5:3
test.h:5:3: (3) [ RecordTypeLoc ] struct X::Y
test.h:3:8: (2) [ CXXConstructorDecl ] 0x331dfa0 inline constexpr X() noexcept
test.h:3:8: (3) [ CompoundStmt ] 0x331e488 CompoundStmt 0x331e488 <./test.h:3:8>

test.h:3:8: (3) [ CXXConstructExpr ] 0x331e428 CXXConstructExpr 0x331e428 <./test.h:3:8> 'struct X::Y' 'void (void) noexcept'

test.h:3:8: (3) [ FunctionCall ] 0x32d7320 inline constexpr Y() noexcept
Marked full-info use of decl 0x32d7320 X::Y::Y (from test.h:4:3 <Spelling=./macro.h:1:18>) at test.h:3:8
test.h:3:8: (2) [ CXXConstructorDecl ] 0x331e0b8 inline constexpr X(const X &)
test.h:3:8: (2) [ CXXConstructorDecl ] 0x331e288 inline constexpr X(X &&)
test.h:3:8: (2) [ CXXDestructorDecl ] 0x331e498 inline ~X() noexcept
test.h:3:8: (3) [ CompoundStmt ] 0x331e588 CompoundStmt 0x331e588 <./test.h:3:8>

test.h:3:8: (2) [ Destruction ] struct X::Y
test.h:3:8: (2) [ FunctionCall ] 0x32d77f0 inline ~Y() noexcept
Marked full-info use of decl 0x32d77f0 X::Y::~Y (from test.h:4:3 <Spelling=./macro.h:1:18>) at test.h:3:8
test.cpp:3:6: (1) [ FunctionDecl ] 0x32d7210 void foo()
test.cpp:3:1: (2) [ FunctionProtoType ] 0x32d71c0 void (void)
test.cpp:3:1: (2) [ FunctionProtoTypeLoc ] void (void)
test.cpp:3:1: (3) [ BuiltinType ] 0x327a6b0 void
test.cpp:3:1: (3) [ BuiltinTypeLoc ] void
test.cpp:4:1: (2) [ CompoundStmt ] 0x32d72f0 CompoundStmt 0x32d72f0 <test.cpp:4:1, line:5:1>

--- Calculating IWYU violations for test.h ---
Ignoring use of X::Y::Y (test.h:3:8): member of class
Ignoring use of X::Y::~Y (test.h:3:8): member of class
Mapped macro.h to "macro.h" for F (only candidate)
Mapped test.h to "test.h" for X::Y (only candidate)
Ignoring full use of F (test.h:4:3): #including dfn from "macro.h"
test.h:5:3: warning: X::Y is defined in "test.h", which isn't directly #included.

test.h should add these lines:
#include "test.h"   // for X::Y

test.h should remove these lines:

The full include-list for test.h:
#include "macro.h"  // for F
#include "test.h"   // for X::Y
---
--- Calculating IWYU violations for test.cpp ---
Marked use of include-file  (from "test.h") at Invalid location
Ignoring full use of  (Invalid location): #including dfn from "test.h"

(test.cpp has correct #includes/fwd-decls)
```

**Comment by kimgr** [comment] 2019-03-17 15:50
The log does not appear to match your example above -- the code you've posted does not have a symbol `F`.

I would expect the macro-sensitive use location code (see `GetCanonicalUseLocation`) to possibly make mistakes here, but I don't see any log messages indicating its reasoning (these are at log level 5, and should come out here).

So, not sure yet what's going on, I'll see if I have a change to dig deeper at some point.

**Comment by ryzzn** [comment] 2019-03-20 09:34
> The log does not appear to match your example above -- the code you've posted does not have a symbol `F`.
> 
> I would expect the macro-sensitive use location code (see `GetCanonicalUseLocation`) to possibly make mistakes here, but I don't see any log messages indicating its reasoning (these are at log level 5, and should come out here).
> 
> So, not sure yet what's going on, I'll see if I have a change to dig deeper at some point.

Thanks a lot. The macro `F` in my local code is the macro defined above named `DEFINE_Y`.

**Comment by jru** [comment] 2019-05-02 08:10
I could not reproduce this problem on the latest master. This is what I get:
```
$# ../../../build/bin/include-what-you-use test.cpp

(test.h has correct #includes/fwd-decls)

(test.cpp has correct #includes/fwd-decls)
```

In fact, the -v7 log shows more output in the *test.cpp* file than in your case, so something might have not been right with that setup.

Can you use *clang_8.0* branch and report back?

**Comment by kimgr** [comment] 2019-06-28 11:21
I can't reproduce this either. Closing.

**Closed by kimgr** 2019-06-28 11:21 UTC
