### ISSUE TITLE
iwyu suggest to include std::map for std::regex

### ISSUE THREAD

**Issue by MarcoFalke** [include-what-you-use/include-what-you-use#1110] opened 2022-09-12 10:09 UTC
Steps to reproduce:

```
$ cat /tmp/1.cpp 
#include <regex>
#include <string>

std::regex Reg(const std::string &r) { return std::regex{r}; }

int main() {}
```
```
$ ./bin/include-what-you-use  /tmp/1.cpp 

/tmp/1.cpp should add these lines:
#include <map>      // for map
#include <sstream>  // for basic_stringbuf<>::int_type, basic_stringbuf<>::p...
#include <vector>   // for vector

/tmp/1.cpp should remove these lines:

The full include-list for /tmp/1.cpp:
#include <map>      // for map
#include <regex>    // for regex, _NFA
#include <sstream>  // for basic_stringbuf<>::int_type, basic_stringbuf<>::p...
#include <string>   // for string
#include <vector>   // for vector
---
```
```
$ ./bin/include-what-you-use  --version 
include-what-you-use 0.18 (git:abd5d2b) based on Ubuntu clang version 14.0.0-1ubuntu1

**Comment by kimgr** [comment] 2022-09-12 15:33
Interesting. Does it behave the same if you:

* only default-construct std::regex
* construct std::regex with a pattern, but don't copy it

?

We have some issues with template symbols being attributed to instatiation location, so I'm looking for a pattern.

Also, is this with libc++ or libstdc++?

**Comment by MarcoFalke** [comment] 2022-09-13 12:53
Yeah, this was with libstdc++. `./bin/include-what-you-use -stdlib=libstdc++ /tmp/1.cpp` gives the same result. libc++ gives:


```
$ ./bin/include-what-you-use -stdlib=libc++ /tmp/1.cpp 

/tmp/1.cpp should add these lines:
#include <iosfwd>  // for string

/tmp/1.cpp should remove these lines:
- #include <string>  // lines 2-2

The full include-list for /tmp/1.cpp:
#include <iosfwd>  // for string
#include <regex>   // for regex
---
```

Switching to default-construction is fine:

```
$ ./bin/include-what-you-use -stdlib=libstdc++ /tmp/1.cpp 

(/tmp/1.cpp has correct #includes/fwd-decls)
```

Removing the copy keeps the bug:

```
$ cat /tmp/1.cpp && ./bin/include-what-you-use -stdlib=libstdc++ /tmp/1.cpp 
#include <regex>
#include <string>
int main() {std::regex{std::string{}};}

/tmp/1.cpp should add these lines:
#include <map>      // for map
#include <sstream>  // for basic_stringbuf<>::int_type, basic_stringbuf<>::p...
#include <vector>   // for vector

/tmp/1.cpp should remove these lines:

The full include-list for /tmp/1.cpp:
#include <map>      // for map
#include <regex>    // for _NFA, regex
#include <sstream>  // for basic_stringbuf<>::int_type, basic_stringbuf<>::p...
#include <string>   // for string
#include <vector>   // for vector
---

**Comment by kimgr** [comment] 2022-09-13 18:46
Thanks! I wonder what the string ctor is doing with the map. Will look into this in more detail as time permits.

**Comment by kimgr** [comment] 2023-02-23 20:44
> I wonder what the string ctor is doing with the map. Will look into this in more detail as time permits.

I've dug deep into the regex tree of headers, and found a clue. Any non-trivial constructor for `std::regex` calls `__detail::__compile_nfa<_Rx_traits>(...)`, which I think eventually ends up in `regex_automaton.tcc`, `_StateSeq<>::_M_clone()`, which in turn uses `std::map` in its implementation.

This is not an explanation for why `include-what-you-use`  behaves the way it does, it just establishes the link between the `std::regex` constructor and `std::map`.

The IWYU behavior is caused by a long-standing problem with how we misinterpret types in template instantiations. All related issues are tagged https://github.com/include-what-you-use/include-what-you-use/labels/template-spill.

**Comment by kimgr** [comment] 2023-03-05 13:46
Fixed on master as of https://github.com/include-what-you-use/include-what-you-use/commit/ffe6c3fe3a1dac9a4b577f4b07ef378ede933554.

**Closed by kimgr** 2023-03-05 13:46 UTC
Labels: template-spill
