### ISSUE TITLE
Invalid suggestion for templated factories, defaulted arguments and indirect includes

### ISSUE THREAD

**Issue by graveljp** [include-what-you-use/include-what-you-use#1121] opened 2022-10-06 14:58 UTC
IWYU produces invalid recommendations when using `make_unique`-style templates to create objects whose constructor has parameters with default values. See a minimalist example at: https://github.com/graveljp/iwyu-bugs/tree/main/default_param

You can reproduce by doing:
```shell
git clone https://github.com/graveljp/iwyu-bugs.git
cd iwyu-bugs/default_param
include-what-you-use main.cc
```

This outputs:
```
main.cc should add these lines:
#include "bar.h"   // for MakeBar

main.cc should remove these lines:

The full include-list for main.cc:
#include "bar.h"   // for MakeBar
#include "foo.h"   // for Foo
#include "make.h"  // for make
---
```

`main.cc` shouldn't be including `bar.h`. This seems to be caused by a missing header in `foo.h`, adding `#include "bar.h"` there fixes the problem. While this is easily worked around, finding where the missing include is can be tricky and doesn't scale to very large code base that never used IWYU (i.e. with missing `includes` all over the code base).

Tests at on latest master (IWYU at https://github.com/include-what-you-use/include-what-you-use/commit/c1d8dd310a3b2e0601d44ece73fba9bc037e82d1 and LLVM at https://github.com/llvm/llvm-project/commit/bc4bcbcfc820b324f680e8f260691c38052eedc9).

**Comment by graveljp** [comment] 2022-10-07 01:55
It's worth pointing out that clangd (in [UnusedIncludes: Strict](https://clangd.llvm.org/guides/include-cleaner#configuration) mode) also agrees that `main.cc` shouldn't be including `bar.h`.

**Comment by kimgr** [comment] 2022-10-08 14:05
Thanks for the excellent repro case! I know IWYU currently has some confusion around attribution for template instantiations, but I'm not 100% sure of the details. I'll try to look into this, but there's some other stuff in the pipeline (e.g. getting a release out compatible with clang-15), so I can't promise when.

**Comment by graveljp** [comment] 2022-10-09 17:14
I found a simpler case similar to this one, this time involving a defaulted template parameter. See here: https://github.com/graveljp/iwyu-bugs/tree/main/default_template_param. Steps to reproduce:
```
git clone https://github.com/graveljp/iwyu-bugs.git
cd iwyu-bugs/default_template_param
include-what-you-use main.cc
```

This outputs:
```
main.cc should add these lines:
#include "functors.h"    // for Identity
```

Here, the recommendation can be silenced by adding a `// IWYU pragma: export` in `transforms.h`:
```
#include "functors.h"  // IWYU pragma: export
```

Doing so however is not always possible in libraries we don't own.

**Comment by kimgr** [comment] 2022-10-09 20:07
I think I know roughly what's missing. If you search `iwyu_ast_util.cc` for `GetTplTypeResugarMap`, you'll find 5 implementations for building a resugar map for different kinds of template instantiations.

The one(s) being used here -- `GetTplTypeResugarMapForFunction...` -- do not have any mention of default template parameter handling, whereas the corresponding code for class templates does. The way a default template arg is special-cased is by adding a resugar entry from template argument type to `nullptr`.

I don't know if this is very hard to do, or if it was just overlooked for function templates.

I tried wrapping `Transform` in a struct, just to see what would happen, and it seems that makes IWYU recognize the default template arg and say all is well.

**Comment by kimgr** [comment] 2022-10-23 10:22
I've been poking at this off and on, and I can confirm that the following special-case patch makes the testcase behave as expected:
```diff
diff --git a/iwyu_ast_util.cc b/iwyu_ast_util.cc
index 4d6d45e..4a039fd 100644
--- a/iwyu_ast_util.cc
+++ b/iwyu_ast_util.cc
@@ -893,6 +893,15 @@ map<const Type*, const Type*> GetTplTypeResugarMapForFunction(
     }
   }
 
+  for (const Type* type : fn_arg_types) {
+    string name = PrintableType(type);
+    if (name.find("Identity") != string::npos) {
+      retval[type] = nullptr;
+      VERRS(6) << "Adding a function template default type of interest: "
+               << name << "\n";
+    }
+  }
+
   // Log the types we never mapped.
   for (const auto& types : desugared_types) {
     if (!ContainsKey(retval, types.first)) {
```

So by explicitly marking `Identity` as a default template parameter (by mapping it to `nullptr`) in `GetTplTypeResugarMapForFunction`, `iwyu.cc`'s `IsDefaultTemplateParameter` will make the right choice, and cause it to be attributed to the template, not the instantiation.

I'll try to teach `GetTplTypeResugarMapForFunction` to recognize both default template parameters and function default parameters as resugaring to `nullptr`.

**Comment by kimgr** [comment] 2022-10-23 10:48
Aha. Seems like default template parameters for function templates was a new feature in C++11: https://stackoverflow.com/questions/2447458/. I found the following comment in IWYU, which left me a little confused:
```
// One can't have partial template specialization or default template
// args for function templates, [...]
```

But that now makes sense, since this code predates C++11. I wonder how these resugaring routines deal with parameter packs, for example. Let's save that surprise for another day :-)

**Comment by graveljp** [comment] 2022-10-23 14:31
That's an interesting find! That's certainly worth adding support for, I would think that partial template specialization and default template args are pretty commonly used now. I wonder how many post-C++-98 features are still broken. It would be nice if we could use a C++ conformity test suite to check all C++ features at once (https://softwareengineering.stackexchange.com/questions/199708/is-there-a-compliance-test-for-c-compilers).

**Comment by kimgr** [comment] 2022-10-23 14:54
This branch appears to work with the current test suite and your new testcase: https://github.com/kimgr/include-what-you-use/commits/1121-func-template-default. Let me know if you have a chance to try it out.

**Comment by graveljp** [comment] 2022-11-24 21:33
I finally got some time to try your branch. It indeed resolves the problem with default template arguments! Thank you very much.

Unfortunately though, it doesn't resolve the original problem raised by this issue (https://github.com/graveljp/iwyu-bugs/tree/main/default_param).

**Comment by kimgr** [comment] 2022-11-25 20:38
Aha, I hadn't fully appreciated the difference between them before. `default_param` looks like it should be simpler, but actually seems more difficult to solve nicely. The type is picked up by `AstFlattenerVisitor` and then blindly replayed at point of instantiation. I'm not sure how to rip out the types that come in by way of default arguments, but it might be doable.

**Comment by kimgr** [comment] 2024-01-03 13:23
The `default_param` example should be fixed on master as of https://github.com/include-what-you-use/include-what-you-use/commit/5739563b7883e5de2ac3dd829e5753c57013bc04.

I had forgotten about my `default_template_param` branch, but I'll see if I can clean it up and put it up for review separately.

**Closed by kimgr** 2024-01-03 13:23 UTC
