### ISSUE TITLE
inconsistent source of `size_t`

### ISSUE THREAD

**Issue by firewave** [include-what-you-use/include-what-you-use#1142] opened 2022-11-20 13:41 UTC
`test.cpp`
```cpp
#include "test.h"

#include <cstring>

static void f()
{
    size_t pos;
    std::strchr((const char*)NULL, 'i');
}

```

`test.h`
```cpp
#ifndef testH
#define testH

#include <cstddef>
#include <cstring>

void flags() {
    std::size_t pos;
    std::strchr((const char*)NULL, 'i');
}

#endif
```

```
test.h should add these lines:

test.h should remove these lines:
- #include <cstddef>  // lines 4-4

The full include-list for test.h:
#include <cstring>  // for strchr, NULL, size_t
---

test.cpp should add these lines:
#include <cstddef>  // for NULL, size_t

test.cpp should remove these lines:

The full include-list for test.cpp:
#include "test.h"
#include <cstddef>  // for NULL, size_t
#include <cstring>  // for strchr
---
```

**Comment by kimgr** [comment] 2022-11-23 19:16
Curious. See if you can get more information about the decision process with more verbose logging.

**Comment by firewave** [comment] 2022-11-23 23:09
FYI I am using `include-what-you-use 0.18 based on Debian clang version 14.0.6-2`.

**Comment by kimgr** [comment] 2022-11-25 19:41
I get the same results on current mainline (0.19+)

**Comment by firewave** [comment] 2022-11-25 21:05
I forgot a `std::` in the .cpp but that doesn't make a difference.

**Comment by alejandro-colomar** [comment] 2024-08-29 17:56
I've tried some small changes to remove some diagnostics (unused variable and nonnull misuse).  I've also removed some more `std::` prefixes to see if it changed anything.

```c++
alx@debian:~/tmp/iwyu$ cat test.cpp 
#include "test.h"

#include <cstring>

static size_t
f(char *s)
{
    return strchr(s, 'i') - s;
}
```
```c++
alx@debian:~/tmp/iwyu$ cat test.h 
#ifndef testH
#define testH

#include <cstddef>
#include <cstring>

size_t
flags(char *s)
{
    return std::strchr(s, 'i') - s;
}

#endif
```
```c++
alx@debian:~/tmp/iwyu$ iwyu test.cpp 

test.h should add these lines:

test.h should remove these lines:
- #include <cstddef>  // lines 4-4

The full include-list for test.h:
#include <cstring>  // for strchr, size_t
---

test.cpp should add these lines:
#include <cstddef>  // for size_t

test.cpp should remove these lines:

The full include-list for test.cpp:
#include "test.h"
#include <cstddef>  // for size_t
#include <cstring>  // for strchr
---
```

If I remove the remaining `std::`, then iwyu(1) reports everything is fine.  :|

```
$ iwyu --version
include-what-you-use 0.22 based on Debian clang version 18.1.8 (9)
```

**Comment by alejandro-colomar** [comment] 2024-08-29 17:57
Ahh, the issue is solved in master:

```
$ ~/src/iwyu/iwyu/master/.tmp/bin/include-what-you-use test.cpp 

(test.h has correct #includes/fwd-decls)

(test.cpp has correct #includes/fwd-decls)
$ ~/src/iwyu/iwyu/master/.tmp/bin/include-what-you-use --version
include-what-you-use 0.23 (git:2178b31) based on Debian clang version 19.1.0 (++20240724103243+7af27be6633a-1~exp1)
```

**Comment by firewave** [comment] 2024-08-30 15:16
Strange. I still get the following using the latest code:

```
test.h should add these lines:

test.h should remove these lines:
- #include <cstddef>  // lines 4-4

The full include-list for test.h:
#include <cstring>  // for strchr, NULL, size_t
---

test.cpp should add these lines:
#include <cstddef>  // for NULL, size_t

test.cpp should remove these lines:

The full include-list for test.cpp:
#include "test.h"
#include <cstddef>  // for NULL, size_t
#include <cstring>  // for strchr
---
```

**Comment by alejandro-colomar** [comment] 2024-08-30 15:21
Yes, I've rebuilt with the latest master, and it is bad again.  It seems it was temporarily fixed during a short time.

**Comment by alejandro-colomar** [comment] 2024-08-30 15:33
Self correction: I've found that iwyu(1) doesn't show the right version after a rebuild, which leads me to think that maybe that one with which I tested recently that didn't show the problem might have been a build with some changes from some branch.

I thought it was from master because it said `(git:2178b31)`, but that might have been wrong.

I've tried building at that commit from scratch, and it reports the same errors, so it seems this was never fixed in master.

On the other hand, this is another reason to not want those weird mappings.  :)

**Comment by firewave** [comment] 2024-08-30 18:48
> And indeed a build with the removal of mappings applied doesn't report those weird suggestions. It says all mappings are good.

Obviously, since it only has a single source without those additional mappings. The question is why does it prioritize the providing header differently.

**Closed** 2024-09-07 06:18 UTC
