### ISSUE TITLE
assertion using BOOST_FOREACH with IWYU 0.17, clang 13.0.1, and libc++

### ISSUE THREAD

**Issue by justincady** [include-what-you-use/include-what-you-use#1017] opened 2022-03-17 18:57 UTC
Here is the minimal reproducer (Ubuntu):

```
$ cat fail.cc
#include <boost/foreach.hpp>
#include <vector>

static void f()
{
    std::vector<int> v;
    BOOST_FOREACH (int x, v) { (void)x; }
}

$ ./build/bin/include-what-you-use --version
include-what-you-use 0.17 (git:fbd921d) based on Ubuntu clang version 13.0.1-++20220120110924+75e33f71c2da-1~exp1~20220120231001.58

$ ./build/bin/include-what-you-use -nostdinc++ -nostdlib++ -isystem/usr/lib/llvm-13/include/c++/v1/ fail.cc
include-what-you-use: /usr/lib/llvm-13/include/llvm/Support/Casting.h:104: static bool llvm::isa_impl_cl<clang::FunctionDecl, const clang::NamedDecl *>::doit(const From *) [To = clang::FunctionDecl, From = const clang::NamedDecl *]: Assertion `Val && "isa<> used on a null pointer"' failed.
Aborted
```

- LLVM 13 was installed using the instructions at https://apt.llvm.org (`./llvm.sh 13 all`)
- Boost was installed via apt-get (libboost-all-dev)
- Interestingly, if you replace `vector` with `list` in my reproducer, the issue disappears

**Comment by kimgr** [comment] 2022-03-17 19:21
Is there a backtrace for that assertion failure, and a `-Xiwyu - v7` dump of the AST? Based on the from-/to-type, it looks like you're hitting #951.

**Comment by kimgr** [comment] 2022-03-17 19:23
On the other hand, that should only happen for `-std=c++20`, which is not yet the default, I think. Backtrace and log might give more details!

**Comment by justincady** [comment] 2022-03-17 19:42
Attaching the requested information for confirmation:

[backtrace.txt](https://github.com/include-what-you-use/include-what-you-use/files/8289983/backtrace.txt)
[Xiwyu.txt](https://github.com/include-what-you-use/include-what-you-use/files/8289984/Xiwyu.txt)

**Comment by justincady** [comment] 2022-03-17 19:54
I tried cherry picking 7d7fd80 onto 0.17 but still observed the crash. It might be a different issue?

**Comment by kimgr** [comment] 2022-03-17 20:56
Yeah, it's a different thing.

The problem appears to be that the `decl` going into `GetCanonicalUseLocation` is null. Confusingly, with higher verbosity it segfaults on the debug output (`Trying to determine use location for '`) before the assertion has a chance to fire.

I suspect this function returns null, and nobody notices: https://github.com/include-what-you-use/include-what-you-use/blob/master/iwyu_ast_util.cc#L1224

**Comment by justincady** [comment] 2022-03-18 19:44
Along the lines of your "nobody notices null" suspicion, I'm using a local workaround in `iwyu.cc` for the moment:

```
     if (const UsingShadowDecl* shadow_decl = DynCastFrom(used_decl))
       target_decl = shadow_decl->getTargetDecl();

     // Map private decls like __normal_iterator to their public counterpart.
     target_decl = MapPrivateDeclToPublicDecl(target_decl);
-    if (CanIgnoreDecl(target_decl))
+    if (target_decl == nullptr || CanIgnoreDecl(target_decl))
       return;

     const UseFlags use_flags =
         ComputeUseFlags(current_ast_node()) | extra_use_flags;
```

I doubt that snippet is sufficient for a full solution (and frankly that it's even _part_ of a full solution). But it does get me past this issue so I can use IWYU in the interim.

**Comment by kimgr** [comment] 2022-03-21 19:13
@justincady Cool, glad to hear you're unblocked. I'll see if I can figure out what the root cause is here and address it.

**Comment by kimgr** [comment] 2022-03-22 19:47
This looks suspiciously like #989.

**Comment by kimgr** [comment] 2022-04-25 18:48
I'm pretty sure now this is the same issue as #989. Closing as a duplicate.

**Closed by kimgr** 2022-04-25 18:48 UTC

**Comment by kimgr** [comment] 2022-05-19 19:44
See #1051 for a fix.
