### ISSUE TITLE
Add CI suite and code coverage

### ISSUE THREAD

**Issue by Flamefire** [include-what-you-use/include-what-you-use#293] opened 2016-04-19 08:44 UTC
I'm surprised to see no CI set up for IWYU. It is pretty easy (travis), widely used already and allows to check, if IWYU compiles with different compilers and OSs and also run the runtime test and produce coverage results.
The last point gives a great tool to check if the current tests fail to tests some code portions of IWYU

**Comment by vsapsai** [comment] 2016-04-27 05:46
There is a buildbot at http://buildbot.include-what-you-use.com:8010/grid and there is a link to it from http://include-what-you-use.org/ Corresponding repo is [include-what-you-use/iwyu_buildbot](https://github.com/include-what-you-use/iwyu_buildbot).

As for [travis-ci.org](https://travis-ci.org/), I'm not sure it can build IWYU. Main source of build breakage is API changes in Clang. So we want to build IWYU with the latest Clang. The problem is that LLVM+Clang build takes time and can exceed Travis CI limits ([documented here](https://docs.travis-ci.com/user/customizing-the-build/#Build-Timeouts)). I didn't try Travis CI, anybody can try to set up full build with it and see if it works.

As for code coverage, do you expect from web version to give you something that cannot be achieved with checking code coverage locally? I agree that code coverage is nice to have but I think there are more important issues to fix. Just want to clarify that I'm not missing some use cases.

**Comment by Flamefire** [comment] 2016-04-27 08:29
As for travis: I'd rather suggest to stick to a specified version of clang and update manually if required. This has 2 advantages: 1. It is clear, with which version IWYU is/can be build 2. One can use the travis cache, which allows skipping the rebuild of clang when it is not changed.
The container based (sudo-less) environment has got 2 cores for compiling and is often faster anyways. So parallel compiling may be enough to stay in the 50 minutes limit. Although I remember that it did took a lot of time to compile clang. If it is not enough, one can probably use one of the prebuild-binaries (http://llvm.org/releases/download.html)

As for coverage: Sure. But I found the code coverage setup to be "easy enough" to have (although I'm not sure about the python wrapper and the multiple execution here) And it can provide useful without having individuals run this. They can just look at the visualisation, see that some part is not covered and add a test. Or see, when an addition reduces coverage e.g. by a misplaced `if`

**Comment by kimgr** [comment] 2016-04-28 19:55
If you can get an environment up and running, I would be interested in seeing it (I know GitHub integrates well with Travis, too, so it would be generally helpful.)

I've been meaning to set up buildbot slaves for Windows and FreeBSD for years (literally), but I always get stuck on some quirky detail, so if Travis is easier to set up portably, that would be a plus in my book.

**Comment by kimgr** [comment] 2017-10-22 14:17
See also #490. Let's have that PR close this issue.

**Closed** 2017-10-24 19:40 UTC
