### ISSUE TITLE
"should add" a "struct blah;" that's already there

### ISSUE THREAD

**Issue by gperciva** [include-what-you-use/include-what-you-use#682] opened 2019-04-23 03:10 UTC
Thanks for iwyu; it's been really useful for my work!

iwyu 0.12 can suggest adding a line that's already there.  I suspect it has to do with a pointer to an opaque structure in an argument list.  Consider `blah.h`:
```
struct blah;
void use_blah(struct blah * b);
```

I get:
```
$ include-what-you-use --version
include-what-you-use 0.12 based on clang version 8.0.0 (tags/RELEASE_800/final)
$ include-what-you-use blah.h 

blah.h should add these lines:
struct blah;

blah.h should remove these lines:

The full include-list for blah.h:
struct blah;
---
```

**Comment by kimgr** [comment] 2019-04-23 05:11
I remember fixing that bug. I think there was a wrinkle, that this is only allowed in C, not C++, or something. There's a comment about this in the IWYU source somewhere, I need to look it up to be sure. Can post back later.

**Comment by kimgr** [comment] 2019-04-23 06:44
See https://github.com/include-what-you-use/include-what-you-use/issues/123 for the motivation.

As this is C code, IWYU promotes it to a real forward-declaration to avoid `-Wvisibility`. See https://github.com/include-what-you-use/include-what-you-use/blob/master/iwyu.cc#L3936 for some more motivation.

So I guess this is "by design", for what it's worth.

**Comment by gperciva** [comment] 2019-04-24 17:35
Sorry if I've misunderstood anything; compilers are a bit beyond my expertise.  I agree that I need a forward declaration for `struct blah`.  But that's already in the file!  (and yes, if I add another a second `struct blah;`, iwyu still asks for another one.)

**Comment by kimgr** [comment] 2019-04-25 19:41
@gperciva Aah, sorry, I misread the report. I tried this locally and can reproduce. The logs don't give any rationale for why the redundant forward decl should be added...

**Comment by charlemagnelasse** [comment] 2019-05-24 16:43
I see the same problem here:
    struct foobar;
    
    struct foobar *test(struct foobar *asd)
    {
    	return asd;
    }

This currently breaks iwyu for me in Debian Buster

**Comment by larseggert** [comment] 2019-07-01 07:53
Same here

**Comment by kimgr** [comment] 2019-11-02 11:52
I think it has something to do with that exception in C language mode -- this
```
$ cat t.c
struct blah;
void use_blah(struct blah * b);

$ include-what-you-use -xc++ t.c 

t.c should add these lines:

t.c should remove these lines:
- struct blah;  // lines 1-1

The full include-list for t.c:
---
$ include-what-you-use t.c 

t.c should add these lines:
struct blah;

t.c should remove these lines:

The full include-list for t.c:
struct blah;
---
```

shows that the behavior is different between the two. And that only C mode exhibits this weird behavior. I'll look into it.

**Comment by kimgr** [comment] 2019-11-03 10:31
I found the root cause of this after lots of false starts -- we have an `IsForwardDecl` predicate we use to register existing forward declarations. In the 0.12 timeframe that accidentally changed only to handle C++ records (structs, classes) and not C records (structs).

Most of our test suite runs Clang in C++ mode, so coverage was poor.

The fix is trivial, I'll merge it soon (PR linked above if you want to take a look).

**Comment by gperciva** [comment] 2019-11-03 17:42
Thanks for investigating, and it's awesome that the fix is so small!

**Comment by kimgr** [comment] 2019-11-03 20:31
Fixed on master.

**Closed by kimgr** 2019-11-03 20:31 UTC
