### ISSUE TITLE
include what you use shouldn't require a forward ref/header for an override of a virtual method

### ISSUE THREAD

**Issue by ThosRTanner** [include-what-you-use/include-what-you-use#241] opened 2015-12-13 14:22 UTC
This is probably easier to do if you use the C++11 override keyword, but it'd be nice if it behaved like this for any valid override.

for instance

```
 #include "my_interface.h"

class MyImplementation : MyInterface
{
    int SomeMethodFromMyInterface(SomeOtherClass &) override;
}
```

shouldn't need to include the header for SomeOtherClass because it has to be available for you to override methods in MyInterface.

Now clearly if you have some other method that takes SomeOtherClass as a parameter or you have it in a data member, that's another issue.  But I think if you are overriding a class, you shouldn't need to duplicate all the headers/forward declarations of that class.

**Comment by kimgr** [comment] 2015-12-13 14:30
Agree, see #105.

I haven't had to time to look at this since, it turned out harder than I expected.

**Comment by kimgr** [comment] 2019-12-26 13:28
Closing as duplicate of #105.

**Closed by kimgr** 2019-12-26 13:28 UTC
