### ISSUE TITLE
IWYU crashes with assertion failure `Name is not a simple identifier`

### ISSUE THREAD

**Issue by odygrd** [include-what-you-use/include-what-you-use#795] opened 2020-05-08 15:05 UTC
Hello, thanks for this tool, it is really helpful !

This bug looks related to this https://github.com/include-what-you-use/include-what-you-use/issues/161

In my code I have

```c++
    #define QUILL_STRING(str)                                                                          \
       [] {                                                                                             \
         using R = union X {                                                                            \
           static constexpr auto value() { return str; }                                                \
         };                                                                                             \
         return R{};                                                                                    \
       }()
```

And I use this in the same file like 

```c++
     PatternFormatter()
      {
       //   Set the default pattern
         _set_pattern(
           QUILL_STRING("%(ascii_time) [%(thread)] %(filename):%(lineno) LOG_%(level_name) "
                        "%(logger_name) - %(message)"));
      }
```

Then IWYU will get a clang assertion here :

```c++
    StringRef getName() const {
       assert(Name.isIdentifier() && "Name is not a simple identifier");
       return getIdentifier() ? getIdentifier()->getName() : "";
    }
```

The exact file this happens if you would like to reproduce is located [here](https://github.com/odygrd/quill/blob/master/quill/include/quill/PatternFormatter.h#L32) 

As a workaround I had to comment out `QUILL_STRING` macro in order to use IWYU.

I got this assertion failure in clang_9.0 branch

**Comment by kimgr** [comment] 2020-05-08 20:21
Here's the smallest repro I've been able to identy:
```
#define QUILL_STRING(str)             \
  [] {                                \
    using R = union X {               \
      static constexpr auto value() { \
        return str;                   \
      }                               \
    };                                \
    return R{};                       \
  }()

void foo() {
  QUILL_STRING("");
}
```

It crashes on this line: https://github.com/include-what-you-use/include-what-you-use/blob/master/iwyu_output.cc#L404

That looks a little suspicious, because it's formatting forward-declares of a class inside a function. Not sure if that's a valid construct at all.

Furthermore, I'm not sure why we're trying to forward-declare anything in this context.

**Comment by mikebwilliams** [comment] 2022-01-03 16:18
I'm also seeing this bug when attempting to compile KiCAD:
```
-c /home/mike/Projects/src/kicad/common/view/view.cpp
Error running 'include-what-you-use': include-what-you-use: /usr/lib/llvm-13/include/clang/AST/Decl.h:277: llvm::StringRef clang::NamedDecl::getName() const: Assertion `Name.isIdentifier() && "Name is not a simple identifier"' failed.
```

Using CMake support:
`cmake -G Ninja -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_EXE_LINKER_FLAGS=-B/home/mike/Projects/src/kicad/mold -DKICAD_BUILD_QA_TESTS=OFF -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_CXX_INCLUDE_WHAT_YOU_USE=include-what-you-use ../`

**Comment by kimgr** [comment] 2022-07-19 10:04
I've played around with this a little off and on, and I can confirm that it's crashing on the lambda expression, because it's unnamed.

While that's easy to fix, e.g. by checking if the `FunctionDecl` lacks an identifier, doing so turns into a really strange suggestion to add a forward decl for `union f::::::X`. So I think it would make sense to try and fix the root cause -- we should not suggest a forward declaration in this case.

But maybe it's better to make sure we don't crash, so the analysis is a little wrong, but at least not entirely broken.

**Comment by kimgr** [comment] 2023-01-02 12:01
I see Quill has retired the `QUILL_STRING` macro, but I finally got around to fixing this bug: https://github.com/include-what-you-use/include-what-you-use/pull/1166.

Rather than patching up `PrintForwardDeclare`, I ended up ignoring uses of declarations that are fully inside a function -- the only way to get your hands on such a decl is by calling the function, so both the function and thereby the declaration must already be included.

**Comment by kimgr** [comment] 2023-01-22 19:36
#1166 is merged, closing as fixed.

**Closed by kimgr** 2023-01-22 19:36 UTC
