### ISSUE TITLE
iwyu(1) should look at things inside #if NOT_TRUE

### ISSUE THREAD

**Issue by alejandro-colomar** [include-what-you-use/include-what-you-use#1069] opened 2022-06-22 09:58 UTC
Let's consider the following code:

```c
# if LINUX_HEADER_EXISTS
    # include <linux_header.h>
# endif
# if FREEBSD_HEADER_EXISTS
    # include <freebsd_header.h>
# endif

# if LINUX
    linux_function();
# elif FREEBSD
    fbsd_function();
# endif
```

Currently, iwyu(1) suggests to remove the FreeBSD include in Linux.  It shouldn't.  I don't know if we should add a complete list of symbols defined by systems to fix this...

**Comment by kimgr-spire** [comment] 2022-07-05 11:23
Duplicate of #1020, closing

**Comment by kimgr** [comment] 2022-07-05 11:25
Duplicate of #1020, closing

**Closed by kimgr** 2022-07-05 11:25 UTC
